# Generated by Django 3.2 on 2021-10-03 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
import yojna.models.department_media
import yojna.models.scheme_media
import yojna.models.scheme_registration_media


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('adhaar_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Gender', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('profile_pic', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('caste', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('mobile_number_verified_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('bpl_dharak', models.BigIntegerField(blank=True, default=None, null=True)),
                ('role', models.CharField(blank=True, choices=[('Department clerk 1', 'Department clerk 1'), ('Department clerk 2', 'Department clerk 2'), ('Department admin hod', 'Department admin hod'), ('Master collector dpo', 'Master collector dpo'), ('User', 'User')], default=('User', 'User'), max_length=100, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('address', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, default=None, max_length=64, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='department_children', to='yojna.departmentmodel')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchemeModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, default=None, max_length=256, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('scheme_document_no', models.IntegerField(blank=True, db_index=True, default=None, null=True)),
                ('sample', models.FileField(blank=True, default=None, null=True, upload_to='media')),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('department', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='yojna.departmentmodel')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='scheme_children', to='yojna.schememodel')),
            ],
            options={
                'verbose_name': 'Scheme',
                'verbose_name_plural': 'Schemes',
                'db_table': 'scheme',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchemeRegistrationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('In Progress', 'In Progress'), ('Labarthi', 'Labarthi')], default=('Pending', 'Pending'), max_length=64, null=True)),
                ('application_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('raised_query', models.TextField(blank=True, default=None, null=True)),
                ('hod_query', models.TextField(blank=True, default=None, null=True)),
                ('cheque_letter', models.FileField(blank=True, default=None, null=True, upload_to='cheques_letter/')),
                ('scheme', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheme_registrations', to='yojna.schememodel')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scheme Registration',
                'verbose_name_plural': 'Scheme Registrations',
                'db_table': 'scheme_registration',
                'ordering': ['scheme'],
            },
        ),
        migrations.CreateModel(
            name='User_documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User_Document',
                'verbose_name_plural': 'User_Documents',
                'db_table': 'user_document',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='upajivikesathi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umedwar_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('paripurn_patta', models.CharField(blank=True, max_length=1000, null=True)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email_id', models.EmailField(default=None, max_length=254)),
                ('shaishnik_patrata', models.CharField(blank=True, max_length=1000, null=True)),
                ('adhaar_no', models.CharField(blank=True, max_length=100, null=True)),
                ('courses', models.CharField(blank=True, max_length=100, null=True)),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upajivikesathi',
            },
        ),
        migrations.CreateModel(
            name='SubdepartmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, default=None, max_length=64, null=True)),
                ('department', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sub_department', to='yojna.departmentmodel')),
            ],
            options={
                'verbose_name': 'Subdepartment',
                'verbose_name_plural': 'Subdepartments',
                'db_table': 'sub_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SectorModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, default=None, max_length=64, null=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sector_children', to='yojna.sectormodel')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'db_table': 'sector',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchemeRegistrationMediaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, choices=[('जातीचे प्रमाणपत्र', 'जातीचे प्रमाणपत्र'), ('शेतीचा ७/१२ व ८ अ उतारा', 'शेतीचा ७/१२ व ८ अ उतारा'), ('आधार कार्ड', 'आधार कार्ड'), ('पासपोर्ट', 'पासपोर्ट'), ('रहिवासी दाखला', 'रहिवासी दाखला'), ('निवडणुक ओळखपत्र', 'निवडणुक ओळखपत्र'), ('मालमत्ता नोंदपत्र', 'मालमत्ता नोंदपत्र'), ('उत्पन्न प्रमाणपत्र', 'उत्पन्न प्रमाणपत्र'), ('रेशन कार्ड', 'रेशन कार्'), ('वडिलांचे मृत्यू प्रमाणपत्र (आवश्यक असल्यास)', 'वडिलांचे मृत्यू प्रमाणपत्र (आवश्यक असल्यास)'), ('१० वी किंवा १२ वी परीक्षेची गुणपत्रिका', '१० वी किंवा १२ वी परीक्षेची गुणपत्रिका'), ('वसतिगृह प्रमाणपत्र (आवश्यक असल्यास)', 'वसतिगृह प्रमाणपत्र (आवश्यक असल्यास)'), ('पतीचे उत्पन्न प्रमाणपत्र (अर्जदार जर स्त्री आहे आणि विवाहित असल्यास)', 'पतीचे उत्पन्न प्रमाणपत्र (अर्जदार जर स्त्री आहे आणि विवाहित असल्यास)'), ('मागासवर्गीय जातीचे प्रमाणपत्र', 'मागासवर्गीय जातीचे प्रमाणपत्र'), ('ग्रामपंचायत सचिवाचा रहिवासी प्रमाणपत्र', 'ग्रामपंचायत सचिवाचा रहिवासी प्रमाणपत्र'), ('विवाह नोंदणी दाखला', 'विवाह नोंदणी दाखला'), ('जागा उपलब्ध असल्याचे प्रमाणपत्र', 'जागा उपलब्ध असल्याचे प्रमाणपत्र'), ('महिला बचत गट सुरु असल्याचे प्रमाणपत्र', 'महिला बचत गट सुरु असल्याचे प्रमाणपत्र'), ('शाळासोडल्याचा दाखला', 'शाळासोडल्याचा दाखला'), ('ओलिताची सोय असल्याचे प्रमाणपत्र', 'ओलिताची सोय असल्याचे प्रमाणपत्र'), ('वयाचा दाखला', 'वयाचा दाखला'), ('शेतीचा नकाशा', 'शेतीचा नकाशा')], default=None, max_length=128, null=True)),
                ('arza', models.FileField(blank=True, default=None, null=True, upload_to=yojna.models.scheme_registration_media.scheme_registration_media_directory_path)),
                ('file_path', models.FileField(blank=True, default=None, null=True, upload_to=yojna.models.scheme_registration_media.scheme_registration_media_directory_path)),
                ('scheme_registration', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheme_registration_media', to='yojna.schemeregistrationmodel')),
            ],
            options={
                'verbose_name': 'Scheme Registration Media',
                'verbose_name_plural': 'Scheme Registration Media',
                'db_table': 'scheme_registration_media',
                'ordering': ['scheme_registration'],
            },
        ),
        migrations.AddField(
            model_name='schememodel',
            name='subdepartment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheme', to='yojna.subdepartmentmodel'),
        ),
        migrations.CreateModel(
            name='SchemeMediaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('category', models.CharField(blank=True, choices=[('information', 'Information'), ('registration', 'Registration')], default=None, max_length=64, null=True)),
                ('file_path', models.FileField(blank=True, default=None, null=True, upload_to=yojna.models.scheme_media.scheme_directory_path)),
                ('scheme', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheme_media', to='yojna.schememodel')),
            ],
            options={
                'verbose_name': 'Scheme media',
                'verbose_name_plural': 'Scheme media',
                'db_table': 'scheme_media',
                'ordering': ['scheme__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='pramod_mah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umedwar_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('paripurn_patta', models.CharField(blank=True, max_length=1000, null=True)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email_id', models.EmailField(default=None, max_length=254)),
                ('shaishnik_patrata', models.CharField(blank=True, max_length=1000, null=True)),
                ('adhaar_no', models.CharField(blank=True, max_length=100, null=True)),
                ('courses', models.CharField(blank=True, max_length=100, null=True)),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pramod_mah',
            },
        ),
        migrations.CreateModel(
            name='pra_dhan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umedwar_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('paripurn_patta', models.CharField(blank=True, max_length=1000, null=True)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email_id', models.EmailField(default=None, max_length=254)),
                ('shaishnik_patrata', models.CharField(blank=True, max_length=1000, null=True)),
                ('adhaar_no', models.CharField(blank=True, max_length=100, null=True)),
                ('courses', models.CharField(blank=True, max_length=100, null=True)),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pra_dhan',
            },
        ),
        migrations.CreateModel(
            name='jilha_pur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umedwar_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('paripurn_patta', models.CharField(blank=True, max_length=1000, null=True)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email_id', models.EmailField(default=None, max_length=254)),
                ('shaishnik_patrata', models.CharField(blank=True, max_length=1000, null=True)),
                ('adhaar_no', models.CharField(blank=True, max_length=100, null=True)),
                ('courses', models.CharField(blank=True, max_length=100, null=True)),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jilha_pur',
            },
        ),
        migrations.CreateModel(
            name='DocumentlinkModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=1000, null=True)),
                ('link', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('scheme', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheme_documents', to='yojna.schememodel')),
            ],
            options={
                'verbose_name': 'doc_tables',
                'verbose_name_plural': 'doc_tables',
                'db_table': 'doc_table',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='din_dayal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umedwar_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('paripurn_patta', models.CharField(blank=True, max_length=1000, null=True)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email_id', models.EmailField(default=None, max_length=254)),
                ('shaishnik_patrata', models.CharField(blank=True, max_length=1000, null=True)),
                ('adhaar_no', models.CharField(blank=True, max_length=100, null=True)),
                ('courses', models.CharField(blank=True, max_length=100, null=True)),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'din_dayal',
            },
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='sector',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='yojna.sectormodel'),
        ),
        migrations.CreateModel(
            name='DepartmentMediaModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('file_path', models.FileField(blank=True, default=None, null=True, upload_to=yojna.models.department_media.department_directory_path)),
                ('department', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_media', to='yojna.departmentmodel')),
            ],
            options={
                'verbose_name': 'Department media',
                'verbose_name_plural': 'Department media',
                'db_table': 'department_media',
                'ordering': ['department__name'],
            },
        ),
        migrations.CreateModel(
            name='andh_vyaktinsathi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('caste', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('education', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('married', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('income', models.BigIntegerField(blank=True, default=None, null=True)),
                ('handicap_type', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('percent', models.FloatField(blank=True, default=None, null=True)),
                ('handicap_certificate_no', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('form_date', models.DateField(blank=True, default=None, null=True)),
                ('business', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('adhar_card_no', models.IntegerField(blank=True, default=None, null=True)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('avashak_seva', models.TextField(blank=True, default=None, null=True)),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_image')),
                ('previous_benefit', models.BooleanField(blank=True, default=None, null=True)),
                ('signature', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Andha_Vyaktisathi',
            },
        ),
        migrations.AddField(
            model_name='usermodel',
            name='department',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.departmentmodel'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
