# Generated by Django 3.2 on 2021-10-11 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andh_vyaktinsathi',
            name='signature',
        ),
        migrations.AlterField(
            model_name='andh_vyaktinsathi',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign'),
        ),
        migrations.AlterField(
            model_name='schememodel',
            name='name',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='subdepartmentmodel',
            name='name',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='ramai_gharkul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('fa_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('cu_address', models.TextField(blank=True, default=None, null=True)),
                ('ghar_address', models.TextField(blank=True, default=None, null=True)),
                ('pe_address', models.TextField(blank=True, default=None, null=True)),
                ('kshetrafal', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('birth_place', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('caste', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('education', models.CharField(blank=True, default=None, max_length=400, null=True)),
                ('business', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('ration_no', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('fa_business', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('income', models.BigIntegerField(blank=True, default=None, null=True)),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_image')),
                ('signature', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('apply_date', models.DateField(blank=True, default=None, null=True)),
                ('name_1', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('pradhanya', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Ramai_Gharkul',
            },
        ),
    ]
