# Generated by Django 3.2 on 2021-10-11 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0002_auto_20211011_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='mini_tra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('gat_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('karya_address', models.TextField(blank=True, default=None, null=True)),
                ('bachat_no', models.IntegerField(blank=True, default=None, null=True)),
                ('anu_no', models.IntegerField(blank=True, default=None, null=True)),
                ('itar_no', models.IntegerField(blank=True, default=None, null=True)),
                ('registration_no', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('registration_date', models.DateField(blank=True, default=None, null=True)),
                ('bachat_info', models.TextField(blank=True, default=None, null=True)),
                ('place', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('app_date', models.DateField(blank=True, default=None, null=True)),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_image')),
                ('signature', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Mini_Tra',
            },
        ),
    ]
