# Generated by Django 3.2 on 2021-10-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0003_mini_tra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mini_tra',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='mini_tra',
            name='signature',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media'),
        ),
    ]
