# Generated by Django 3.2 on 2021-10-16 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0011_sankalp_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jilha_pur',
            name='kau_prashikshan',
        ),
    ]
