# Generated by Django 3.2 on 2021-10-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0012_remove_jilha_pur_kau_prashikshan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='din_dayal',
            name='kau_prashikshan',
        ),
    ]
