# Generated by Django 3.2 on 2021-10-16 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0013_remove_din_dayal_kau_prashikshan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pra_dhan',
            name='kau_prashikshan',
        ),
    ]
