# Generated by Django 3.2 on 2021-10-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0014_remove_pra_dhan_kau_prashikshan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pramod_mah',
            name='kau_prashikshan',
        ),
    ]
