# Generated by Django 3.2 on 2021-10-16 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0015_remove_pramod_mah_kau_prashikshan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sankalp_skill',
            name='kau_prashikshan',
        ),
    ]
