# Generated by Django 3.2 on 2021-10-16 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0016_remove_sankalp_skill_kau_prashikshan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upajivikesathi',
            name='kau_prashikshan',
        ),
    ]
