# Generated by Django 3.2 on 2021-10-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0019_shahu_fule'),
    ]

    operations = [
        migrations.AddField(
            model_name='vyaktinsathi',
            name='hudda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vyaktinsathi',
            name='pramanpatra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vyaktinsathi',
            name='purava',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign'),
        ),
        migrations.AddField(
            model_name='vyaktinsathi',
            name='thikan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vyaktinsathi',
            name='vyakti_karyakarta1',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign'),
        ),
    ]
