# Generated by Django 3.2 on 2021-10-24 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0020_auto_20211024_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='lokshahir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('jilha_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('paripurn_patta', models.CharField(blank=True, max_length=1000, null=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('purava', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('education', models.CharField(blank=True, max_length=1000, null=True)),
                ('business', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('jat', models.CharField(blank=True, max_length=100, null=True)),
                ('pramanpatra', models.CharField(blank=True, max_length=100, null=True)),
                ('hudda', models.CharField(blank=True, max_length=100, null=True)),
                ('thikan', models.CharField(blank=True, max_length=100, null=True)),
                ('patni_hyat', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('samajik', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('arj_pur', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('anujati', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('vyakti_sahitya', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('jya_sanstha', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('samkaly_kshetra', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('karyakartya', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('yapurvi_bahu', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('karkarta_sadhya', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('vidhanmandal', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('vyakti_karyakarta', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('vyakti_karyakarta1', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('shifaras', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('itar', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('form_date', models.DateField(blank=True, default=None, null=True)),
                ('signature', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lokshahir',
            },
        ),
    ]
