# Generated by Django 3.2 on 2021-10-24 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0023_karmavir'),
    ]

    operations = [
        migrations.CreateModel(
            name='bharat_sanstha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('jilha_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('adhi1_date', models.DateField(blank=True, default=None, null=True)),
                ('adhi2_date', models.DateField(blank=True, default=None, null=True)),
                ('adhi1', models.CharField(blank=True, max_length=100, null=True)),
                ('adhi2', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('paripurn_patta', models.CharField(blank=True, max_length=1000, null=True)),
                ('sambandhit', models.CharField(blank=True, max_length=1000, null=True)),
                ('upvidhi', models.CharField(blank=True, max_length=1000, null=True)),
                ('padadhi1_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('padadhi2_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('mob1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('mob2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('arj_pur', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('anubhav', models.CharField(blank=True, max_length=100, null=True)),
                ('lekha_pari', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('varshik_aha', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('swatantra_lekha', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('sambandhit_sanstha', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('upkram', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('vyaktigat', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('sadar_sansthes', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('vaishishtya', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('vaishishtya1', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('dakhla', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('name2', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('pari_name1', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('pari_name2', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('pari_name3', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('from1', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('from2', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('from3', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('pari_date1', models.DateField(blank=True, default=None, null=True)),
                ('pari_date2', models.DateField(blank=True, default=None, null=True)),
                ('pari_date3', models.DateField(blank=True, default=None, null=True)),
                ('signature', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bharat_sanstha',
            },
        ),
    ]
