# Generated by Django 3.2 on 2021-10-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0026_ravidas_sanstha'),
    ]

    operations = [
        migrations.AddField(
            model_name='shahu_fule',
            name='vaishishtya1',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign'),
        ),
        migrations.AlterField(
            model_name='shahu_fule',
            name='dakhla',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign'),
        ),
    ]
