# Generated by Django 3.2 on 2021-10-24 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0027_auto_20211024_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='magasvargiy_mula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('jilha_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('signature', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('name2', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('name1', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('moth_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('fa_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('sthanik_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('paripurn_patta', models.CharField(blank=True, max_length=1000, null=True)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('kayam_patta', models.CharField(blank=True, max_length=1000, null=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('birth_place', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('adhaar_no', models.CharField(blank=True, max_length=100, null=True)),
                ('email_id', models.EmailField(default=None, max_length=254)),
                ('pan1_no', models.CharField(blank=True, max_length=100, null=True)),
                ('pan2_no', models.CharField(blank=True, max_length=100, null=True)),
                ('pravarg', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('pravarg_file', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('divyang_file', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('divyang', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('iyatta', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('previous_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('previous_address', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('bank_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('bank_no', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('ifsc', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('aajar', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('aajar_file', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('gunha', models.BooleanField(blank=True, default=None, null=True)),
                ('shasakiy_seva', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('income', models.CharField(blank=True, max_length=100, null=True)),
                ('varsh1', models.CharField(blank=True, max_length=100, null=True)),
                ('varsh2', models.CharField(blank=True, max_length=100, null=True)),
                ('varsh3', models.CharField(blank=True, max_length=100, null=True)),
                ('iyatta1', models.CharField(blank=True, max_length=100, null=True)),
                ('iyatta2', models.CharField(blank=True, max_length=100, null=True)),
                ('iyatta3', models.CharField(blank=True, max_length=100, null=True)),
                ('takka1', models.CharField(blank=True, max_length=100, null=True)),
                ('takka2', models.CharField(blank=True, max_length=100, null=True)),
                ('takka3', models.CharField(blank=True, max_length=100, null=True)),
                ('maha_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('abhyaskram', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('pas_varsh', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('charitrya', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('sakshi_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('sakshi_signature', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('palak_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('palak_signature', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('vidya_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('vidya_signature', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'magasvargiy_mula',
            },
        ),
    ]
