# Generated by Django 3.2 on 2021-11-13 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0035_gatai_kamgar'),
    ]

    operations = [
        migrations.CreateModel(
            name='hami_yojna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karyalay1', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('form_date', models.DateField(blank=True, default=None, null=True)),
                ('karyalay2', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('yoj_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('jat', models.CharField(blank=True, max_length=100, null=True)),
                ('mu_post', models.CharField(blank=True, max_length=100, null=True)),
                ('taluka', models.CharField(blank=True, max_length=100, null=True)),
                ('jilha', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('adhaar_no', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=1000, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('khate_kr', models.CharField(blank=True, max_length=100, null=True)),
                ('shakha', models.CharField(blank=True, max_length=100, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=1000, null=True)),
                ('jamin_prakar', models.CharField(blank=True, max_length=100, null=True)),
                ('gat_kr', models.CharField(blank=True, max_length=100, null=True)),
                ('kshetra', models.CharField(blank=True, max_length=100, null=True)),
                ('pike', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('tuti_kshetra', models.CharField(blank=True, max_length=100, null=True)),
                ('sinchan', models.CharField(blank=True, max_length=100, null=True)),
                ('sinchan_kalavadhi', models.CharField(blank=True, max_length=100, null=True)),
                ('vij_jodni', models.BooleanField(blank=True, default=None, null=True)),
                ('gruh_vyavstha', models.BooleanField(blank=True, default=None, null=True)),
                ('majur', models.BooleanField(blank=True, default=None, null=True)),
                ('shetkari_varg', models.CharField(blank=True, max_length=100, null=True)),
                ('daridrya', models.BooleanField(blank=True, default=None, null=True)),
                ('bplkard', models.CharField(blank=True, max_length=100, null=True)),
                ('nondani_fee', models.BooleanField(blank=True, default=None, null=True)),
                ('shri', models.CharField(blank=True, max_length=100, null=True)),
                ('padnam', models.CharField(blank=True, max_length=100, null=True)),
                ('karyalay3', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('shetkari_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('signature', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hami_yojna',
            },
        ),
    ]
