# Generated by Django 3.2 on 2021-11-15 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0036_hami_yojna'),
    ]

    operations = [
        migrations.CreateModel(
            name='vaiyaktik_sabhasad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shri', models.CharField(blank=True, max_length=1000, null=True)),
                ('form_date', models.DateField(blank=True, default=None, null=True)),
                ('name3', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('form_date1', models.DateField(blank=True, default=None, null=True)),
                ('singh', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_image')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('patta', models.CharField(blank=True, max_length=1000, null=True)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('email_id', models.EmailField(default=None, max_length=254)),
                ('patta1', models.CharField(blank=True, max_length=1000, null=True)),
                ('business', models.CharField(blank=True, max_length=1000, null=True)),
                ('name1', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('patta2', models.CharField(blank=True, max_length=1000, null=True)),
                ('mobile_number1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vaiyaktik_sabhasad',
            },
        ),
        migrations.CreateModel(
            name='sanstha_sabhasad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sansname', models.CharField(blank=True, max_length=1000, null=True)),
                ('form_date', models.DateField(blank=True, default=None, null=True)),
                ('name3', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('form_date1', models.DateField(blank=True, default=None, null=True)),
                ('singh', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('sansthaname', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('patta', models.CharField(blank=True, max_length=1000, null=True)),
                ('non_kr', models.CharField(blank=True, max_length=100, null=True)),
                ('satyaprat', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('sachivname1', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('patta2', models.CharField(blank=True, max_length=1000, null=True)),
                ('granth_sankhya', models.CharField(blank=True, max_length=100, null=True)),
                ('sabh_sankhya', models.CharField(blank=True, max_length=100, null=True)),
                ('devghevi', models.CharField(blank=True, max_length=100, null=True)),
                ('tharav_kr', models.CharField(blank=True, max_length=100, null=True)),
                ('tharav_date', models.DateField(blank=True, default=None, null=True)),
                ('satyaprat1', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('karya_sadasya1', models.CharField(blank=True, max_length=100, null=True)),
                ('karya_sadasya2', models.CharField(blank=True, max_length=100, null=True)),
                ('karya_sadasya3', models.CharField(blank=True, max_length=100, null=True)),
                ('karya_sadasya4', models.CharField(blank=True, max_length=100, null=True)),
                ('karya_sadasya5', models.CharField(blank=True, max_length=100, null=True)),
                ('karya_sadasya6', models.CharField(blank=True, max_length=100, null=True)),
                ('karya_sadasya7', models.CharField(blank=True, max_length=100, null=True)),
                ('itar', models.CharField(blank=True, max_length=1000, null=True)),
                ('shri', models.CharField(blank=True, max_length=1000, null=True)),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sanstha_sabhasad',
            },
        ),
        migrations.CreateModel(
            name='masemari_arth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('san', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('talav', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ekun', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('sabhasad', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('sahi', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'masemari_arth',
            },
        ),
    ]
