# Generated by Django 3.2 on 2021-11-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0038_matsyasampada'),
    ]

    operations = [
        migrations.AddField(
            model_name='jilha_pur',
            name='course_prashikshan1',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jilha_pur',
            name='course_prashikshan2',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jilha_pur',
            name='prashikshan1',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='jilha_pur',
            name='prashikshan2',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
