# Generated by Django 3.2 on 2021-11-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0044_auto_20211122_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanstha_sabhasad',
            name='shikka',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign'),
        ),
    ]
