# Generated by Django 3.2 on 2021-11-29 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0045_sanstha_sabhasad_shikka'),
    ]

    operations = [
        migrations.CreateModel(
            name='polis_bhartipurva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('fa_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('paripurn_patta', models.CharField(blank=True, max_length=1000, null=True)),
                ('dharma', models.CharField(blank=True, max_length=100, null=True)),
                ('dharma_dakhla', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('jat', models.CharField(blank=True, max_length=100, null=True)),
                ('varshik_utpanna', models.CharField(blank=True, max_length=100, null=True)),
                ('dakhla', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('rahivasi', models.BooleanField(blank=True, default=None, null=True)),
                ('rahi_dakhla', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('hsc', models.CharField(blank=True, max_length=100, null=True)),
                ('hsc_dakhla', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('unchi', models.CharField(blank=True, max_length=100, null=True)),
                ('chhati', models.CharField(blank=True, max_length=100, null=True)),
                ('fugvun', models.CharField(blank=True, max_length=100, null=True)),
                ('seva_kard', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('birth_date1', models.DateField(blank=True, default=None, null=True)),
                ('varsh', models.CharField(blank=True, max_length=100, null=True)),
                ('mahina', models.CharField(blank=True, max_length=100, null=True)),
                ('divas', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('name1', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('form_date', models.DateField(blank=True, default=None, null=True)),
                ('mobile_number1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'polis_bhartipurva',
            },
        ),
    ]
