# Generated by Django 3.2 on 2021-11-29 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0049_mada_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='balsangopan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('education', models.CharField(blank=True, max_length=1000, null=True)),
                ('palak_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('patta', models.CharField(blank=True, max_length=1000, null=True)),
                ('palak_name1', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('patta1', models.CharField(blank=True, max_length=1000, null=True)),
                ('nate', models.CharField(blank=True, max_length=100, null=True)),
                ('income', models.CharField(blank=True, max_length=100, null=True)),
                ('buisness', models.CharField(blank=True, max_length=1000, null=True)),
                ('aai', models.BooleanField(blank=True, default=None, null=True)),
                ('vadil', models.BooleanField(blank=True, default=None, null=True)),
                ('mahiti', models.CharField(blank=True, max_length=100, null=True)),
                ('sthiti', models.CharField(blank=True, max_length=100, null=True)),
                ('bhau', models.CharField(blank=True, max_length=100, null=True)),
                ('bahin', models.CharField(blank=True, max_length=100, null=True)),
                ('aaji', models.CharField(blank=True, max_length=100, null=True)),
                ('name1', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('patta2', models.CharField(blank=True, max_length=1000, null=True)),
                ('signature', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'balsangopan',
            },
        ),
    ]
