# Generated by Django 3.2 on 2021-11-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0058_swadhar_yoj_pot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swadhar_yoj',
            name='pravesh_date1',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='swadhar_yoj',
            name='pravesh_date2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='swadhar_yoj',
            name='pravesh_date3',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
