# Generated by Django 3.2 on 2021-11-30 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0059_auto_20211130_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swadhar_yoj',
            name='income_cer',
        ),
    ]
