# Generated by Django 3.2 on 2021-11-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0060_remove_swadhar_yoj_income_cer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatai_kamgar',
            name='jaga_tapshil',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_image'),
        ),
    ]
