# Generated by Django 3.2 on 2022-03-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0066_asthivyang_vyakti_divyang_sanganak_divyang_xerox_karnbadhir_vyakti_magas_shilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andh_vyaktinsathi',
            name='previous_benefit',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
