# Generated by Django 3.2 on 2022-03-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0067_alter_andh_vyaktinsathi_previous_benefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dharmik_alp',
            name='anudan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dharmik_alp',
            name='nidhi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='polis_bhartipurva',
            name='rahivasi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zakir_hus',
            name='malkichi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zakir_hus',
            name='upkram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
