# Generated by Django 3.2 on 2022-03-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0069_auto_20220326_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punyshlok_ahilya',
            name='doc1',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='punyshlok_ahilya',
            name='doc2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='punyshlok_ahilya',
            name='doc3',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='punyshlok_ahilya',
            name='doc4',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='punyshlok_ahilya',
            name='doc5',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='punyshlok_ahilya',
            name='doc6',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='punyshlok_ahilya',
            name='doc7',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='punyshlok_ahilya',
            name='doc8',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='punyshlok_ahilya',
            name='doc9',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
