# Generated by Django 3.2 on 2022-03-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0070_auto_20220326_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='upajivikesathi',
            name='kau_prashikshan',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='upajivikesathi',
            name='rahivasi',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
