# Generated by Django 3.2 on 2022-03-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0071_auto_20220326_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='bpl',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='bpl_dharak',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
