# Generated by Django 3.2 on 2022-04-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0072_auto_20220331_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='din_dayal',
            name='kau_prashikshan',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jilha_pur',
            name='kau_prashikshan',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pra_dhan',
            name='kau_prashikshan',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pramod_mah',
            name='kau_prashikshan',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sankalp_skill',
            name='kau_prashikshan',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='din_dayal',
            name='rahivasi',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jilha_pur',
            name='rahivasi',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pra_dhan',
            name='rahivasi',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pramod_mah',
            name='rahivasi',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sankalp_skill',
            name='rahivasi',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
