# Generated by Django 3.2 on 2022-04-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0073_auto_20220405_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matsyasampada',
            name='experienced',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matsyasampada',
            name='lease',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matsyasampada',
            name='own',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matsyasampada',
            name='trained',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
