# Generated by Django 3.2.4 on 2022-04-12 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0074_auto_20220405_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='dubhte_janawar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=170, null=True)),
                ('jat', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('janwar', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('sudharit', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('kilo', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('sign', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('nav', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('patta', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dubhte_janawar',
            },
        ),
        migrations.CreateModel(
            name='anusuchit_50takke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('photo_id', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('mukampost', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('taluka', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('pincode', models.IntegerField(blank=True, default=None, null=True)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('age_year', models.IntegerField(blank=True, default=None, null=True)),
                ('age_month', models.IntegerField(blank=True, default=None, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('daridrya_yn', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('daridry_cf', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('jaga_yn', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('prashikshan_yn', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('anujamat_yn', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('bhumihin_yn', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('bachatgat_yn', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('bachatgat_name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('bachatgat_address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bachatgat_shetra', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('berozgar_yn', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('sevayojna_cf', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('sign', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('nav', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('place', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('dinank', models.DateField(blank=True, default=None, null=True)),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'anusuchit_50takke',
            },
        ),
    ]
