# Generated by Django 3.2.4 on 2022-04-27 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0077_thakkar'),
    ]

    operations = [
        migrations.CreateModel(
            name='anusuchit_shabri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jilha', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=180, null=True)),
                ('jat', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('birthdate', models.DateField(blank=True, default=None, null=True)),
                ('age', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('married', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('son', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('daughter', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('total_child', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('ladies', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('gents', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('total', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('education', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('yojna', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('samu_vayaktik', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('daridrya_cardno', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('income', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('income_src', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('jaga', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('alpa_bhudharak', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('alpa_cf', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('bhumihin', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('bhumihin_cf', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('vidhva', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('vidhva_cf', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('vidhur', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('vidhur_cf', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('ghatsphotit', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('ghatsphotit_cf', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('bhukampgrast', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('bhukamp_cf', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('apang', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('apang_cf', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('dharangrast', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('dharangrast_cf', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('majhi_sainik', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('sainik_cf', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('labh', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('yojna1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('year1', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('yojna2', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('year2', models.CharField(blank=True, default=None, max_length=8, null=True)),
                ('dinank', models.DateField(blank=True, default=None, null=True)),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('sign', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('place', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'anusuchit_shabri',
            },
        ),
    ]
