# Generated by Django 3.2.4 on 2022-04-27 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0078_anusuchit_shabri'),
    ]

    operations = [
        migrations.CreateModel(
            name='bhumihin_daridrya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jilha', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('huswife_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=180, null=True)),
                ('anu_jamat', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('adim_jamat', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('striya', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('vidhwa', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('bhumihin_yn', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('daridrya_yn', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('daridrya_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('talathi_cf', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('age', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('labhdharak_yn', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('tapshil', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('jamin_yn', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('atikraman_yn', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('pratidnyapatra', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('hamipatra', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('mashagat', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('income_yn', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('water_src', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('yojnalabh_yn', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('yojna1', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('year1', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('yojna2', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('year2', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('dinank', models.DateField(blank=True, default=None, null=True)),
                ('place', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('sign', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bhumihin_daridrya',
            },
        ),
    ]
