# Generated by Django 3.2.4 on 2022-04-28 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0079_bhumihin_daridrya'),
    ]

    operations = [
        migrations.CreateModel(
            name='samuhik_vivah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanstha_name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('sanstha_add', models.CharField(blank=True, default=None, max_length=110, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('reg_no', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('thikani', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('time', models.TimeField(blank=True, default=None, null=True)),
                ('padadhikari', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('hudda', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('var_name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('var_birhtdate', models.DateField(blank=True, default=None, null=True)),
                ('var_age', models.IntegerField(blank=True, default=None, null=True)),
                ('var_dharma', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('var_jat', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('var_potjat', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('var_edu', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('var_add', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('var_gav', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('var_tal', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('var_dist', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('var_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('vadhu_name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('vadhu_birhtdate', models.DateField(blank=True, default=None, null=True)),
                ('vadhu_age', models.IntegerField(blank=True, default=None, null=True)),
                ('vadhu_dharma', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('vadhu_jat', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('vadhu_potjat', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('vadhu_edu', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('vadhu_add', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('vadhu_gav', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('vadhu_tal', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('vadhu_dist', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('vadhu_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('tapal_add', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('niwas', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('karyalay', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('other', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('sanstha', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('vivah_thikan', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('vivahdate', models.DateField(blank=True, default=None, null=True)),
                ('vivah_type', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('var_firstvivah', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('vadhu_firstvivah', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('var_vidur', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('vadhu_vidhva', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('bfor_yojna', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('anya_zp', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('dinank', models.DateField(blank=True, default=None, null=True)),
                ('place', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('var_nm', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('var_sign', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('var_photo', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('vadhu_nm', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('vadhu_sign', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('vadhu_photo', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'samuhik_vivah',
            },
        ),
    ]
