# Generated by Django 3.2.4 on 2022-05-06 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0080_samuhik_vivah'),
    ]

    operations = [
        migrations.CreateModel(
            name='anusuchit_swechha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('father_palak', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('nate', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('father_edu', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('mother_name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('mom_edu', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('jat', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('potjat', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('dharma', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=7, null=True)),
                ('nationality', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('birthdate', models.DateField(blank=True, default=None, null=True)),
                ('birth_letter', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('mukam', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('post', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('taluka', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('jilha', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('mukam2', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('post2', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('taluka2', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('jilha2', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('mobile2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('language', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('std', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('reason', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('passed', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('year', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('percent', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('grade', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('income', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('business', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('kutumb', models.IntegerField(blank=True, default=None, null=True)),
                ('student', models.IntegerField(blank=True, default=None, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('place', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('sign', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('palak', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('mukam3', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('post3', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('taluka3', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('jilha3', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('janmjat', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('palya', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('std3', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('saksh1', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('saksh2', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('palak_nav', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('palak_sahi', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('dinank', models.DateField(blank=True, default=None, null=True)),
                ('thikan', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('vidyarthi_swaksh', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('palak_swaksh', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'anusuchit_swechha',
            },
        ),
    ]
