# Generated by Django 3.2.4 on 2022-05-07 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0081_anusuchit_swechha'),
    ]

    operations = [
        migrations.CreateModel(
            name='divyang_avyang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arjadar_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('patta', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('dinank', models.DateField(blank=True, default=None, null=True)),
                ('jilha', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('vivah_dinank', models.DateField(blank=True, default=None, null=True)),
                ('var_nav', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('var_apangpraman', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('var_shikshan', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('var_vyavsay', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('var_karyalay', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('var_address', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('vadhu_nav', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('vadhu_apangpraman', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('vadhu_shikshan', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('vadhu_vyavsay', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('vadhu_karyalay', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('vadhu_address', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('vivah_date', models.DateField(blank=True, default=None, null=True)),
                ('vivah_place', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('vivah_type', models.CharField(blank=True, default=None, max_length=7, null=True)),
                ('var_pratham', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('vadhu_pratham', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('var_vidur', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('vadhu_vidhva', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('bfor_yojna', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('anya_zp', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('zp_name', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('zp_dinank', models.DateField(blank=True, default=None, null=True)),
                ('zp_arzadinank', models.DateField(blank=True, default=None, null=True)),
                ('satkar', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('where', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('when', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('var_sign', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('vadhu_sign', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'divyang_avyang',
            },
        ),
    ]
