# Generated by Django 3.2.4 on 2022-05-07 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0082_divyang_avyang'),
    ]

    operations = [
        migrations.CreateModel(
            name='divyadivyang_anudan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('wife_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('husband_birth', models.DateField(blank=True, default=None, null=True)),
                ('wife_birth', models.DateField(blank=True, default=None, null=True)),
                ('husband_age', models.IntegerField(blank=True, default=None, null=True)),
                ('wife_age', models.IntegerField(blank=True, default=None, null=True)),
                ('husband_gender', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('wife_gender', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('husband_caste', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('wife_caste', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('husband_edu', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('wife_edu', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('income', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('vivah_date', models.DateField(blank=True, default=None, null=True)),
                ('husdivyang_type', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('hus_percent', models.FloatField(blank=True, default=None, null=True)),
                ('wifedivyang_type', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('wife_percent', models.FloatField(blank=True, default=None, null=True)),
                ('hus_certificateno', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('huscertificate_date', models.DateField(blank=True, default=None, null=True)),
                ('wife_certificateno', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('wifecertificate_date', models.DateField(blank=True, default=None, null=True)),
                ('hus_vyavsay', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('wife_vyavsay', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('husadhar_no', models.IntegerField(blank=True, default=None, null=True)),
                ('wifeadhar_no', models.IntegerField(blank=True, default=None, null=True)),
                ('hus_address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('wifemaher_address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('mobile_no1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('mobile_no2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('yojna_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('benefit', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('hus_photo', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('wife_photo', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('hus_sign', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('wife_sign', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'divyadivyang_anudan',
            },
        ),
    ]
