# Generated by Django 3.2.4 on 2022-05-07 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0083_divyadivyang_anudan'),
    ]

    operations = [
        migrations.CreateModel(
            name='swayamrojgar_divyang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('fa_husname', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('patra_address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('birthdate', models.DateField(blank=True, default=None, null=True)),
                ('daridrya_yn', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('daridrya_num', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('apang_type', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('apang_swarup', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('apang_certificate', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('certificate_yn', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('vyavsay', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('income', models.IntegerField(blank=True, default=None, null=True)),
                ('olakh1', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('olakh2', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('photo_yn', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('education', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('shaley_edu', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('technical_edu', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('other_edu', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('naukri_exp', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('business_exp', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('samaj_exp', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ration_yn', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('arja_vyavsay', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('vyavsay_swarup', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('vyavsay_ghatna', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('malak_bhagidar', models.CharField(blank=True, default=None, max_length=350, null=True)),
                ('vyavsay_reason', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bhandval', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('kayam_bhandval', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('khelte_bhandval', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('yojna_tartud', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('guntavlele_bhandval', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('prakalp_yn', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('samajkalyan_khate', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('spardha', models.CharField(blank=True, default=None, max_length=350, null=True)),
                ('mal_vikri', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('other_help', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('other_arza', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('dinank', models.DateField(blank=True, default=None, null=True)),
                ('place', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('signature', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'swayamrojgar_divyang',
            },
        ),
    ]
