# Generated by Django 3.2.4 on 2022-05-07 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0084_swayamrojgar_divyang'),
    ]

    operations = [
        migrations.CreateModel(
            name='antarjatiy_vivah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arjadar_name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=180, null=True)),
                ('dinank', models.DateField(blank=True, default=None, null=True)),
                ('mob_no1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('mob_no2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('vivah_date', models.DateField(blank=True, default=None, null=True)),
                ('var_name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('var_dharma', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('var_caste', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('var_edu', models.CharField(blank=True, default=None, max_length=90, null=True)),
                ('var_vyavsay', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('var_karyalay', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('var_address', models.CharField(blank=True, default=None, max_length=180, null=True)),
                ('var_adharno', models.BigIntegerField(blank=True, default=None, null=True)),
                ('vadhu_name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('vadhu_dharma', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('vadhu_caste', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('vadhu_edu', models.CharField(blank=True, default=None, max_length=90, null=True)),
                ('vadhu_vyavsay', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('vadhu_karyalay', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('vadhu_address', models.CharField(blank=True, default=None, max_length=180, null=True)),
                ('vadhu_jilha', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('vadhu_adharno', models.BigIntegerField(blank=True, default=None, null=True)),
                ('vivah_date1', models.DateField(blank=True, default=None, null=True)),
                ('vivah_place', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('vivah_type', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('var_firstvivah', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('vadhu_firstvivah', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('var_vidur', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('vadhu_vidhva', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('bfor_yojna', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('anya_zp', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('satkar', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('where', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('when', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('bankname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('account_no', models.BigIntegerField(blank=True, default=None, null=True)),
                ('ifsc_no', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('var_sign', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('vadhu_sign', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'antarjatiy_vivah',
            },
        ),
    ]
