# Generated by Django 3.2.4 on 2022-06-07 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0087_adivasividyarthi_engraji'),
    ]

    operations = [
        migrations.CreateModel(
            name='sainikshala_adi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shikshanik_satra', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('vidyarthi_name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('vadil_name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('father_mob', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('aai_name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('aai_mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('sampurn_patta', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('tahsil_jilha', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('jat_yn', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('jat_praman', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('birth_num', models.DateField(blank=True, default=None, null=True)),
                ('birth_char', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('birthplace', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('nationality', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('school_name', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('school_address', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('medium', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sainikshala_adi',
            },
        ),
    ]
