# Generated by Django 3.2.4 on 2022-06-10 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0088_sainikshala_adi'),
    ]

    operations = [
        migrations.CreateModel(
            name='eklavya_school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std1', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('std2', models.CharField(blank=True, default=None, max_length=2, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('birth_place', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('jamat', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('rahivasi_yn', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('nate', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('father_add', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('mother_name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('income', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('vyavsay', models.CharField(blank=True, default=None, max_length=35, null=True)),
                ('school', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('marks', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('std3', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('paas', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('members', models.IntegerField(blank=True, default=None, null=True)),
                ('bank_name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('branch', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('acc_no', models.BigIntegerField(blank=True, default=None, null=True)),
                ('ifsc', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('adhar_no', models.BigIntegerField(blank=True, default=None, null=True)),
                ('sign', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eklavya_school',
            },
        ),
    ]
