# Generated by Django 3.2.4 on 2022-06-10 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0090_kendra_prashikshan_kendravarti_utpanna'),
    ]

    operations = [
        migrations.CreateModel(
            name='shaskiy_ashramshala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gav', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('tal', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('jil', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('eyatta', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('dina', models.DateField(blank=True, default=None, null=True)),
                ('thik', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('swakshari', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('nav', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('saral_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('purn_nav', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('father_name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('mother_name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('jababi_vyakti', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('mukam', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('post', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('taluka', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('dist', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('patta', models.CharField(blank=True, default=None, max_length=180, null=True)),
                ('birthdate', models.DateField(blank=True, default=None, null=True)),
                ('birth_akshar', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('birthplace', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('dharm', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('jat', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('last_std', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('year', models.CharField(blank=True, default=None, max_length=9, null=True)),
                ('takke', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('acc_no', models.BigIntegerField(blank=True, default=None, null=True)),
                ('bank_name', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('branch', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('ifsc', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('adhar_no', models.BigIntegerField(blank=True, default=None, null=True)),
                ('adhar_name', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('link_yn', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('brosis_name1', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('std1', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('nate1', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('brosis_name2', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('std2', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('nate2', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('dinank', models.DateField(blank=True, default=None, null=True)),
                ('sign', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shaskiy_ashramshala',
            },
        ),
    ]
