# Generated by Django 3.2.4 on 2022-06-10 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0091_shaskiy_ashramshala'),
    ]

    operations = [
        migrations.CreateModel(
            name='shaskiy_postbasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('patta', models.CharField(blank=True, default=None, max_length=180, null=True)),
                ('jat', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('birthdate', models.DateField(blank=True, default=None, null=True)),
                ('age', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('education', models.CharField(blank=True, default=None, max_length=70, null=True)),
                ('income', models.CharField(blank=True, default=None, max_length=13, null=True)),
                ('labh_yn', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('nokri_yn', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('nondni_no', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('abhyaskram', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('thikan', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('dinank', models.DateField(blank=True, default=None, null=True)),
                ('sign', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='media/divyang_person_sign')),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shaskiy_postbasic',
            },
        ),
    ]
