# Generated by Django 3.2.4 on 2022-06-10 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0092_shaskiy_postbasic'),
    ]

    operations = [
        migrations.CreateModel(
            name='kisan_credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('father', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('caste', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('uid_oreid', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('adhar_no', models.CharField(blank=True, default=None, max_length=28, null=True)),
                ('id_proof', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('id_no', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('dist', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('subdist', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('village', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('ifsc', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('state_name', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('dist_name', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('bank', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schememodel')),
                ('scheme_register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.schemeregistrationmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kisan_credit',
            },
        ),
    ]
