# Generated by Django 4.1 on 2022-10-18 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0097_auto_20220614_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='subdepartment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='yojna.subdepartmentmodel'),
        )
        
    ]
