# Generated by Django 4.1 on 2022-11-24 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0099_alter_andh_vyaktinsathi_adhar_card_no_and_more'),
    ]

    
