# Generated by Django 4.1 on 2022-12-06 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0100_rajarshi_shahuscholar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swadhar_yoj',
            name='fee',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
       
    ]
