# Generated by Django 4.1.7 on 2023-04-27 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('yojna', '0101_alter_swadhar_yoj_fee_rajarshi_shahuscholar'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemeregistrationmodel',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        
    ]
