from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from yojna.models import UserModel,SchemeModel,SchemeRegistrationModel

class anusuchit_scholar(models.Model):
    name = models.CharField(max_length=80,default=None,null=True,blank=True)
    email_id = models.EmailField(null=False, blank=False, default=None)
    address = models.CharField(max_length=140,default=None,null=True,blank=True)
    mob_no = models.CharField(max_length=40,default=None,null=True,blank=True)
    jat = models.CharField(max_length=40,default=None,null=True,blank=True)
    potjat = models.CharField(max_length=40,default=None,null=True,blank=True)
    jat_cf = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    birthdate = models.DateField(default=None,null=True,blank=True)
    birth_char = models.CharField(max_length=50,default=None,null=True,blank=True)
    birth_cf = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    father_name = models.CharField(max_length=80,default=None,null=True,blank=True)
    father_add = models.CharField(max_length=140,default=None,null=True,blank=True)
    father_mob = models.CharField(max_length=40,default=None,null=True,blank=True)
    father_email = models.EmailField(null=False, blank=False, default=None)
    busi_job = models.CharField(max_length=80,default=None,null=True,blank=True)
    office_add = models.CharField(max_length=80,default=None,null=True,blank=True)
    office_mob = models.CharField(max_length=40,default=None,null=True,blank=True)
    office_email = models.EmailField(null=False, blank=False, default=None)
    income = models.CharField(max_length=15,default=None,null=True,blank=True)
    income_cf = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    
    hsc_passyear = models.CharField(max_length=15,default=None,null=True,blank=True)
    hsc_institute = models.CharField(max_length=60,default=None,null=True,blank=True)
    hsc_marks = models.CharField(max_length=10,default=None,null=True,blank=True)
    hsc_percent = models.CharField(max_length=15,default=None,null=True,blank=True)
    ug_passyear = models.CharField(max_length=15,default=None,null=True,blank=True)
    ug_institute = models.CharField(max_length=60,default=None,null=True,blank=True)
    ug_marks = models.CharField(max_length=10,default=None,null=True,blank=True)
    ug_percent = models.CharField(max_length=15,default=None,null=True,blank=True)
    pg_passyear = models.CharField(max_length=15,default=None,null=True,blank=True)
    pg_institute = models.CharField(max_length=60,default=None,null=True,blank=True)
    pg_marks = models.CharField(max_length=10,default=None,null=True,blank=True)
    pg_percent = models.CharField(max_length=15,default=None,null=True,blank=True)

    name1 = models.CharField(max_length=50,default=None,null=True,blank=True)
    age1 = models.CharField(max_length=2,default=None,null=True,blank=True)
    nate1 = models.CharField(max_length=25,default=None,null=True,blank=True)
    business1 = models.CharField(max_length=35,default=None,null=True,blank=True)
    income1 = models.CharField(max_length=15,default=None,null=True,blank=True)
    name2 = models.CharField(max_length=50,default=None,null=True,blank=True)
    age2 = models.CharField(max_length=2,default=None,null=True,blank=True)
    nate2 = models.CharField(max_length=25,default=None,null=True,blank=True)
    business2 = models.CharField(max_length=35,default=None,null=True,blank=True)
    income2 = models.CharField(max_length=15,default=None,null=True,blank=True)
    name3 = models.CharField(max_length=50,default=None,null=True,blank=True)
    age3 = models.CharField(max_length=2,default=None,null=True,blank=True)
    nate3 = models.CharField(max_length=25,default=None,null=True,blank=True)
    business3 = models.CharField(max_length=35,default=None,null=True,blank=True)
    income3 = models.CharField(max_length=15,default=None,null=True,blank=True)
    name4 = models.CharField(max_length=50,default=None,null=True,blank=True)
    age4 = models.CharField(max_length=2,default=None,null=True,blank=True)
    nate4 = models.CharField(max_length=25,default=None,null=True,blank=True)
    business4 = models.CharField(max_length=35,default=None,null=True,blank=True)
    income4 = models.CharField(max_length=15,default=None,null=True,blank=True)
    name5 = models.CharField(max_length=50,default=None,null=True,blank=True)
    age5 = models.CharField(max_length=2,default=None,null=True,blank=True)
    nate5 = models.CharField(max_length=25,default=None,null=True,blank=True)
    business5 = models.CharField(max_length=35,default=None,null=True,blank=True)
    income5 = models.CharField(max_length=15,default=None,null=True,blank=True)

    abhyas = models.CharField(max_length=50,default=None,null=True,blank=True)
    kalavadhi = models.CharField(max_length=25,default=None,null=True,blank=True)
    intitute = models.CharField(max_length=80,default=None,null=True,blank=True)
    university = models.CharField(max_length=120,default=None,null=True,blank=True)
    college_add = models.CharField(max_length=120,default=None,null=True,blank=True)
    college_mob = PhoneNumberField(unique=True, blank=True)
    college_email = models.EmailField(null=False, blank=False, default=None)

    shikshan1 = models.CharField(max_length=50,null=True, blank=True, default=None)
    shikshan2 = models.CharField(max_length=50,null=True, blank=True, default=None)
    shikshan3 = models.CharField(max_length=50,null=True, blank=True, default=None)
    shikshan4 = models.CharField(max_length=50,null=True, blank=True, default=None)
    pariksha1 = models.CharField(max_length=50,null=True, blank=True, default=None)
    pariksha2 = models.CharField(max_length=50,null=True, blank=True, default=None)
    pariksha3 = models.CharField(max_length=50,null=True, blank=True, default=None)
    pariksha4 = models.CharField(max_length=50,null=True, blank=True, default=None)
    niwas1 = models.CharField(max_length=50,null=True, blank=True, default=None)
    niwas2 = models.CharField(max_length=50,null=True, blank=True, default=None)
    niwas3 = models.CharField(max_length=50,null=True, blank=True, default=None)
    niwas4 = models.CharField(max_length=50,null=True, blank=True, default=None)
    other1 = models.CharField(max_length=50,null=True, blank=True, default=None)
    other2 = models.CharField(max_length=50,null=True, blank=True, default=None)
    other3 = models.CharField(max_length=50,null=True, blank=True, default=None)
    other4 = models.CharField(max_length=50,null=True, blank=True, default=None)
    total1 = models.CharField(max_length=50,null=True, blank=True, default=None)
    total2 = models.CharField(max_length=50,null=True, blank=True, default=None)
    total3 = models.CharField(max_length=50,null=True, blank=True, default=None)
    total4 = models.CharField(max_length=50,null=True, blank=True, default=None)

    bank_name1 = models.CharField(max_length=50,null=True, blank=True, default=None)
    branch1 = models.CharField(max_length=80,null=True, blank=True, default=None)
    acc_no1 = models.BigIntegerField(null=True, blank=True, default=None)
    sortcode1 = models.CharField(max_length=30,null=True, blank=True, default=None)
    swiftcode1 = models.CharField(max_length=30,null=True, blank=True, default=None)
    ibpn_no1 = models.CharField(max_length=30,null=True, blank=True, default=None)
    bank_name2 = models.CharField(max_length=50,null=True, blank=True, default=None)
    branch2 = models.CharField(max_length=80,null=True, blank=True, default=None)
    acc_no2 = models.BigIntegerField(null=True, blank=True, default=None)
    sortcode2 = models.CharField(max_length=30,null=True, blank=True, default=None)
    swiftcode2 = models.CharField(max_length=30,null=True, blank=True, default=None)
    ibpn_no2 = models.CharField(max_length=30,null=True, blank=True, default=None)

    other_scholar = models.CharField(max_length=100,null=True, blank=True, default=None)
    dinank = models.DateField(default=None,null=True,blank=True)
    place = models.CharField(max_length=50,default=None,null=True,blank=True)
    stu_nm = models.CharField(max_length=50,default=None,null=True,blank=True)
    stu_sign = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    palak_nm = models.CharField(max_length=50,default=None,null=True,blank=True)
    palak_sign = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    photo = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)

    user=models.ForeignKey(UserModel, on_delete=models.CASCADE, null=True)
    scheme=models.ForeignKey(SchemeModel, on_delete=models.CASCADE, null=True)
    scheme_register=models.ForeignKey(SchemeRegistrationModel, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = "anusuchit_scholar"
    def __str__(self) -> str:
        return str(self.name)