from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from yojna.models import SchemeModel,SchemeRegistrationModel,UserModel

class dharmik_alp(models.Model):
    sch_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    patta= models.CharField(max_length=1000,null=True, blank=True, default=None)
    mobile_number = PhoneNumberField( blank=True)
    email_id = models.EmailField(null=False, blank=False, default=None)
    code= models.CharField(max_length=100,null=True, blank=True, default=None)
    sch_sanstha= models.CharField(max_length=1000,null=True, blank=True, default=None)
    sanstha_patta = models.CharField(max_length=1000, null=True, blank=True)
    mobile_number1 = PhoneNumberField( blank=True)
    pracharya_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    acc_no = models.CharField(max_length=100, null=True, blank=True)
    ifsc = models.CharField(max_length=100, null=True, blank=True)
    nondani_kr1 = models.CharField(max_length=100, null=True, blank=True)
    nondani_kr2 = models.CharField(max_length=100, null=True, blank=True)
    nondani_kr3 = models.CharField(max_length=100, null=True, blank=True)
    nondani_kr4 = models.CharField(max_length=100, null=True, blank=True)
    nondani_kr5 = models.CharField(max_length=100, null=True, blank=True)
    tarikh = models.DateField(default=None,null=True,blank=True)
    manjur1 = models.CharField(max_length=100, null=True, blank=True)
    manjur2 = models.CharField(max_length=100, null=True, blank=True)
    manjur3 = models.CharField(max_length=100, null=True, blank=True)
    chalu1 = models.CharField(max_length=100, null=True, blank=True)
    chalu2 = models.CharField(max_length=100, null=True, blank=True)
    chalu3 = models.CharField(max_length=100, null=True, blank=True)
    abhyaskram = models.CharField(max_length=100, null=True, blank=True)
    madhyam = models.CharField(max_length=100, null=True, blank=True)
    sankhya = models.CharField(max_length=100, null=True, blank=True)
    imaratimdhe = models.CharField(max_length=100, null=True, blank=True)
    aavashyak_bandh = models.CharField(max_length=100, null=True, blank=True)
    mahila1 = models.CharField(max_length=100, null=True, blank=True)
    mahila2 = models.CharField(max_length=100, null=True, blank=True)
    purush1 = models.CharField(max_length=100, null=True, blank=True)
    purush2 = models.CharField(max_length=100, null=True, blank=True)
    pani = models.CharField(max_length=100, null=True, blank=True)
    nutanikaran1 = models.CharField(max_length=100, null=True, blank=True)
    nutanikaran2 = models.CharField(max_length=100, null=True, blank=True)
    nutanikaran3 = models.CharField(max_length=100, null=True, blank=True)
    nutanikaran4 = models.CharField(max_length=100, null=True, blank=True)
    dagduji1 = models.CharField(max_length=100, null=True, blank=True)
    dagduji2 = models.CharField(max_length=100, null=True, blank=True)
    dagduji3 = models.CharField(max_length=100, null=True, blank=True)
    dagduji4 = models.CharField(max_length=100, null=True, blank=True)
    chhat1 = models.CharField(max_length=100, null=True, blank=True)
    chhat2 = models.CharField(max_length=100, null=True, blank=True)
    chhat3 = models.CharField(max_length=100, null=True, blank=True)
    chhat4 = models.CharField(max_length=100, null=True, blank=True)
    farshi1 = models.CharField(max_length=100, null=True, blank=True)
    farshi2 = models.CharField(max_length=100, null=True, blank=True)
    farshi3 = models.CharField(max_length=100, null=True, blank=True)
    farshi4 = models.CharField(max_length=100, null=True, blank=True)
    kooler1 = models.CharField(max_length=100, null=True, blank=True)
    kooler2 = models.CharField(max_length=100, null=True, blank=True)
    kooler3 = models.CharField(max_length=100, null=True, blank=True)
    kooler4 = models.CharField(max_length=100, null=True, blank=True)
    kits1 = models.CharField(max_length=100, null=True, blank=True)
    kits2 = models.CharField(max_length=100, null=True, blank=True)
    kits3 = models.CharField(max_length=100, null=True, blank=True)
    kits4 = models.CharField(max_length=100, null=True, blank=True)
    pustke_khredi1 = models.CharField(max_length=100, null=True, blank=True)
    pustke_khredi2 = models.CharField(max_length=100, null=True, blank=True)
    pustke_khredi3 = models.CharField(max_length=100, null=True, blank=True)
    pustke_khredi4 = models.CharField(max_length=100, null=True, blank=True)
    itar_khredi1 = models.CharField(max_length=100, null=True, blank=True)
    itar_khredi2 = models.CharField(max_length=100, null=True, blank=True)
    itar_khredi3 = models.CharField(max_length=100, null=True, blank=True)
    itar_khredi4 = models.CharField(max_length=100, null=True, blank=True)
    prayogshala1 = models.CharField(max_length=100, null=True, blank=True)
    prayogshala2 = models.CharField(max_length=100, null=True, blank=True)
    prayogshala3 = models.CharField(max_length=100, null=True, blank=True)
    prayogshala4 = models.CharField(max_length=100, null=True, blank=True)
    sanganak1 = models.CharField(max_length=100, null=True, blank=True)
    sanganak2 = models.CharField(max_length=100, null=True, blank=True)
    sanganak3 = models.CharField(max_length=100, null=True, blank=True)
    sanganak4 = models.CharField(max_length=100, null=True, blank=True)
    sankhya1 = models.CharField(max_length=100, null=True, blank=True)
    sankhya2 = models.CharField(max_length=100, null=True, blank=True)
    sankhya3 = models.CharField(max_length=100, null=True, blank=True)
    sankhya4 = models.CharField(max_length=100, null=True, blank=True)
    printers1 = models.CharField(max_length=100, null=True, blank=True)
    printers2 = models.CharField(max_length=100, null=True, blank=True)
    printers3 = models.CharField(max_length=100, null=True, blank=True)
    printers4 = models.CharField(max_length=100, null=True, blank=True)
    software1 = models.CharField(max_length=100, null=True, blank=True)
    software2 = models.CharField(max_length=100, null=True, blank=True)
    software3 = models.CharField(max_length=100, null=True, blank=True)
    software4 = models.CharField(max_length=100, null=True, blank=True)
    itar_sahity1 = models.CharField(max_length=100, null=True, blank=True)
    itar_sahity2 = models.CharField(max_length=100, null=True, blank=True)
    itar_sahity3 = models.CharField(max_length=100, null=True, blank=True)
    itar_sahity4 = models.CharField(max_length=100, null=True, blank=True)
    swachhtagruhe1 = models.CharField(max_length=100, null=True, blank=True)
    swachhtagruhe2 = models.CharField(max_length=100, null=True, blank=True)
    swachhtagruhe3 = models.CharField(max_length=100, null=True, blank=True)
    swachhtagruhe4 = models.CharField(max_length=100, null=True, blank=True)
    durusti1 = models.CharField(max_length=100, null=True, blank=True)
    durusti2 = models.CharField(max_length=100, null=True, blank=True)
    durusti3 = models.CharField(max_length=100, null=True, blank=True)
    durusti4 = models.CharField(max_length=100, null=True, blank=True)
    new_swachhtagruhe1 = models.CharField(max_length=100, null=True, blank=True)
    new_swachhtagruhe2 = models.CharField(max_length=100, null=True, blank=True)
    new_swachhtagruhe3 = models.CharField(max_length=100, null=True, blank=True)
    new_swachhtagruhe4 = models.CharField(max_length=100, null=True, blank=True)
    furniture1 = models.CharField(max_length=100, null=True, blank=True)
    furniture2 = models.CharField(max_length=100, null=True, blank=True)
    furniture3 = models.CharField(max_length=100, null=True, blank=True)
    furniture4 = models.CharField(max_length=100, null=True, blank=True)
    benches1 = models.CharField(max_length=100, null=True, blank=True)
    benches2 = models.CharField(max_length=100, null=True, blank=True)
    benches3 = models.CharField(max_length=100, null=True, blank=True)
    benches4 = models.CharField(max_length=100, null=True, blank=True)
    inverter1 = models.CharField(max_length=100, null=True, blank=True)
    inverter2 = models.CharField(max_length=100, null=True, blank=True)
    inverter3 = models.CharField(max_length=100, null=True, blank=True)
    inverter4 = models.CharField(max_length=100, null=True, blank=True)
    xerox1 = models.CharField(max_length=100, null=True, blank=True)
    xerox2 = models.CharField(max_length=100, null=True, blank=True)
    xerox3 = models.CharField(max_length=100, null=True, blank=True)
    xerox4 = models.CharField(max_length=100, null=True, blank=True)
    material1 = models.CharField(max_length=100, null=True, blank=True)
    material2 = models.CharField(max_length=100, null=True, blank=True)
    material3 = models.CharField(max_length=100, null=True, blank=True)
    material4 = models.CharField(max_length=100, null=True, blank=True)
    elearning1 = models.CharField(max_length=100, null=True, blank=True)
    elearning2 = models.CharField(max_length=100, null=True, blank=True)
    elearning3 = models.CharField(max_length=100, null=True, blank=True)
    elearning4 = models.CharField(max_length=100, null=True, blank=True)
    hardware1 = models.CharField(max_length=100, null=True, blank=True)
    hardware2 = models.CharField(max_length=100, null=True, blank=True)
    hardware3 = models.CharField(max_length=100, null=True, blank=True)
    hardware4 = models.CharField(max_length=100, null=True, blank=True)
    ekun1 = models.CharField(max_length=100, null=True, blank=True)
    ekun2 = models.CharField(max_length=100, null=True, blank=True)
    ekun3 = models.CharField(max_length=100, null=True, blank=True)
    ekun4 = models.CharField(max_length=100, null=True, blank=True)
    ekun_rakkam1 = models.CharField(max_length=100, null=True, blank=True)
    anudan = models.CharField(max_length=50, null=True, blank=True)
    arthik_vrsh1 = models.CharField(max_length=100, null=True, blank=True)
    arthik_vrsh2 = models.CharField(max_length=100, null=True, blank=True)
    rakkam1 = models.CharField(max_length=100, null=True, blank=True)
    rakkam2 = models.CharField(max_length=100, null=True, blank=True)
    prayojan1 = models.CharField(max_length=100, null=True, blank=True)
    prayojan2 = models.CharField(max_length=100, null=True, blank=True)
    nidhi = models.CharField(max_length=50, null=True, blank=True)
    mi = models.CharField(max_length=100, null=True, blank=True)
    hudda = models.CharField(max_length=100, null=True, blank=True)
    pramanit = models.CharField(max_length=100, null=True, blank=True)
    sansthedvara = models.CharField(max_length=100, null=True, blank=True)
    sanchalit = models.CharField(max_length=100, null=True, blank=True)
    signature = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    name = models.CharField(max_length=1000, null=True, blank=True)
    shikka = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    photo1 = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    photo2 = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    user=models.ForeignKey(UserModel, on_delete=models.CASCADE, null=True)
    scheme=models.ForeignKey(SchemeModel, on_delete=models.CASCADE, null=True)
    scheme_register=models.ForeignKey(SchemeRegistrationModel, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = "dharmik_alp"
        

