from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from yojna.models import SchemeModel,SchemeRegistrationModel,UserModel


class jilhaudyog(models.Model):
    prakaran_no = models.CharField(max_length=100,null=True, blank=True, default=None)
    pra_date = models.DateField(default=None,null=True,blank=True)
    name = models.CharField(max_length=100,null=True, blank=True, default=None)
    money_char = models.CharField(max_length=100,null=True, blank=True, default=None)
    money_num = models.CharField(max_length=100,null=True, blank=True, default=None)
    candname = models.CharField(max_length=150,null=True, blank=True, default=None)
    candaddress = models.CharField(max_length=150,null=True, blank=True, default=None)
    mobile_number = PhoneNumberField(blank=True)
    varg_jat = models.CharField(max_length=100,null=True, blank=True, default=None)
    sthayi_vid = models.CharField(max_length=100,null=True, blank=True, default=None)
    khrch = models.CharField(max_length=100,null=True, blank=True, default=None)
    compor_pedhi = models.CharField(max_length=100,null=True, blank=True, default=None)
    business_name = models.CharField(max_length=100,null=True, blank=True, default=None)
    work = models.CharField(max_length=100,null=True, blank=True, default=None)
    ownerpartner_nameinvest = models.CharField(max_length=150,null=True, blank=True, default=None)
    sanchalak_name = models.CharField(max_length=100,null=True, blank=True, default=None)
    construction = models.CharField(max_length=100,null=True, blank=True, default=None)
    land = models.CharField(max_length=100,null=True, blank=True, default=None)
    machines = models.CharField(max_length=100,null=True, blank=True, default=None)
    work_expenditure = models.CharField(max_length=100,null=True, blank=True, default=None)
    total = models.CharField(max_length=100,null=True, blank=True, default=None)
    Azamin = models.CharField(max_length=100,null=True, blank=True, default=None)
    Aemarat = models.CharField(max_length=100,null=True, blank=True, default=None)
    Amachine = models.CharField(max_length=100,null=True, blank=True, default=None)
    Atotal_amount = models.CharField(max_length=100,null=True, blank=True, default=None)
    Bzamin = models.CharField(max_length=100,null=True, blank=True, default=None)
    Bemarat = models.CharField(max_length=100,null=True, blank=True, default=None)
    Bmachine = models.CharField(max_length=100,null=True, blank=True, default=None)
    Btotal_amount = models.CharField(max_length=100,null=True, blank=True, default=None)
    business_info = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    paratfed = models.CharField(max_length=100,null=True, blank=True, default=None)
    insurance = models.CharField(max_length=100,null=True, blank=True, default=None)
    bankname = models.CharField(max_length=100,null=True, blank=True, default=None)
    isloan = models.CharField(max_length=100,null=True, blank=True, default=None)
    employees = models.CharField(max_length=100,null=True, blank=True, default=None)
    technician = models.CharField(max_length=100,null=True, blank=True, default=None)
    govenrnment_loan = models.CharField(max_length=100,null=True, blank=True, default=None)
    sambhavya_profit = models.CharField(max_length=100,null=True, blank=True, default=None)
    total_income = models.CharField(max_length=100, null=True, blank=True, default=None)
    mal_exp = models.CharField(max_length=100, null=True, blank=True, default=None)
    majuri_exp = models.CharField(max_length=100, null=True, blank=True, default=None)
    rent_exp = models.CharField(max_length=100, null=True, blank=True, default=None)
    light_exp = models.CharField(max_length=100, null=True, blank=True, default=None)
    kirkol_exp = models.CharField(max_length=100, null=True, blank=True, default=None)
    total_exp = models.CharField(max_length=100, null=True, blank=True, default=None)
    profit = models.CharField(max_length=100, null=True, blank=True, default=None)
    prashaskiy_exp = models.CharField(max_length=100, null=True, blank=True, default=None)
    ownerpartner_exp = models.CharField(max_length=100, null=True, blank=True, default=None)
    intrest_exp = models.CharField(max_length=100, null=True, blank=True, default=None)
    tax_exp = models.CharField(max_length=100, null=True, blank=True, default=None)
    total_poit = models.CharField(max_length=100, null=True, blank=True, default=None)
    onlyprofit = models.CharField(max_length=100, null=True, blank=True, default=None)
    moneywith_u = models.CharField(max_length=100, null=True, blank=True, default=None)
    date = models.DateField(default=None,null=True,blank=True)
    sign = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    kutumb = models.CharField(max_length=100, null=True, blank=True, default=None)
    chitnis = models.CharField(max_length=100, null=True, blank=True, default=None)
    photo = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)

    user=models.ForeignKey(UserModel, on_delete=models.CASCADE, null=True)
    scheme=models.ForeignKey(SchemeModel, on_delete=models.CASCADE, null=True)
    scheme_register=models.ForeignKey(SchemeRegistrationModel, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = "jilhaudyog"
        

