from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from yojna.models import SchemeModel,SchemeRegistrationModel,UserModel

class magasvargiy_mula(models.Model):
    name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    jilha_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    signature = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    name2= models.CharField(max_length=1000,null=True, blank=True, default=None)
    name1= models.CharField(max_length=1000,null=True, blank=True, default=None)
    moth_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    fa_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    sthanik_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    paripurn_patta = models.CharField(max_length=1000, null=True, blank=True)
    mobile_number = PhoneNumberField( blank=True)
    kayam_patta = models.CharField(max_length=1000, null=True, blank=True)
    birth_date = models.DateField(default=None,null=True,blank=True)
    birth_place =  models.CharField(max_length=100, null=True, blank=True)
    mobile_number1 = PhoneNumberField( blank=True)
    adhaar_no = models.CharField(max_length=100, null=True, blank=True)
    email_id = models.EmailField(null=False, blank=False, default=None)
    pan1_no = models.CharField(max_length=100, null=True, blank=True)
    pan2_no = models.CharField(max_length=100, null=True, blank=True)
    pravarg = models.CharField(default=None,null=True,blank=True,max_length=200)
    pravarg_file = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    divyang_file = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    divyang= models.CharField(max_length=1000,null=True, blank=True, default=None)
    iyatta= models.CharField(max_length=1000,null=True, blank=True, default=None)
    previous_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    previous_address= models.CharField(max_length=1000,null=True, blank=True, default=None)
    bank_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    bank_no= models.CharField(max_length=1000,null=True, blank=True, default=None)
    ifsc= models.CharField(max_length=1000,null=True, blank=True, default=None)
    aajar= models.CharField(max_length=1000,null=True, blank=True, default=None)
    aajar_file = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    gunha= models.BooleanField(default=None,null=True,blank=True)
    shasakiy_seva= models.CharField(max_length=1000,null=True, blank=True, default=None)
    income = models.CharField(max_length=100, null=True, blank=True)
    varsh1 = models.CharField(max_length=100, null=True, blank=True)
    varsh2 = models.CharField(max_length=100, null=True, blank=True)
    varsh3 = models.CharField(max_length=100, null=True, blank=True)
    iyatta1 = models.CharField(max_length=100, null=True, blank=True)
    iyatta2 = models.CharField(max_length=100, null=True, blank=True)
    iyatta3 = models.CharField(max_length=100, null=True, blank=True)
    takka1 = models.CharField(max_length=100, null=True, blank=True)
    takka2 = models.CharField(max_length=100, null=True, blank=True)
    takka3 = models.CharField(max_length=100, null=True, blank=True)
    maha_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    abhyaskram= models.CharField(max_length=1000,null=True, blank=True, default=None)
    pas_varsh= models.CharField(max_length=1000,null=True, blank=True, default=None)
    charitrya= models.CharField(max_length=1000,null=True, blank=True, default=None)
    sakshi_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    sakshi_signature = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    palak_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    palak_signature = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    vidya_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    vidya_signature = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    user=models.ForeignKey(UserModel, on_delete=models.CASCADE, null=True)
    scheme=models.ForeignKey(SchemeModel, on_delete=models.CASCADE, null=True)
    scheme_register=models.ForeignKey(SchemeRegistrationModel, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = "magasvargiy_mula"
        

