from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from yojna.models import SchemeModel,SchemeRegistrationModel,UserModel

class matsyasampada(models.Model):
    name =  models.CharField(max_length=1000, null=True, blank=True)
    benificiaries =  models.CharField(max_length=100, null=True, blank=True)
    category =  models.CharField(max_length=100, null=True, blank=True)
    door =  models.CharField(max_length=1000, null=True, blank=True)
    village =  models.CharField(max_length=100, null=True, blank=True)
    dis =  models.CharField(max_length=100, null=True, blank=True)
    state =  models.CharField(max_length=100, null=True, blank=True)
    pin =  models.CharField(max_length=100, null=True, blank=True)
    own = models.CharField(max_length=50, null=True, blank=True)
    area =  models.CharField(max_length=100, null=True, blank=True)
    lease = models.CharField(max_length=50, null=True, blank=True)
    period =  models.CharField(max_length=100, null=True, blank=True)
    site_addr =  models.CharField(max_length=1000, null=True, blank=True)
    village1 =  models.CharField(max_length=100, null=True, blank=True)
    dis1 =  models.CharField(max_length=100, null=True, blank=True)
    state1 =  models.CharField(max_length=100, null=True, blank=True)
    pin1 =  models.CharField(max_length=100, null=True, blank=True)
    land_no = PhoneNumberField( blank=True)
    mobile = PhoneNumberField( blank=True)
    email_id = models.EmailField(null=False, blank=False, default=None)
    total =  models.CharField(max_length=100, null=True, blank=True)
    gen =  models.CharField(max_length=100, null=True, blank=True)
    sc =  models.CharField(max_length=100, null=True, blank=True)
    st =  models.CharField(max_length=100, null=True, blank=True)
    women =  models.CharField(max_length=100, null=True, blank=True)
    govt =  models.CharField(max_length=100, null=True, blank=True)
    total1 =  models.CharField(max_length=100, null=True, blank=True)
    gen1 =  models.CharField(max_length=100, null=True, blank=True)
    sc1 =  models.CharField(max_length=100, null=True, blank=True)
    st1 =  models.CharField(max_length=100, null=True, blank=True)
    women1 =  models.CharField(max_length=100, null=True, blank=True)
    govt1 =  models.CharField(max_length=100, null=True, blank=True)
    total2 =  models.CharField(max_length=100, null=True, blank=True)
    gen2 =  models.CharField(max_length=100, null=True, blank=True)
    sc2 =  models.CharField(max_length=100, null=True, blank=True)
    st2 =  models.CharField(max_length=100, null=True, blank=True)
    women2 =  models.CharField(max_length=100, null=True, blank=True)
    govt2 =  models.CharField(max_length=100, null=True, blank=True)
    pro_item =  models.CharField(max_length=100, null=True, blank=True)
    type_pro = models.CharField(max_length=100,default=None,null=True,blank=True)
    pre_inv = models.CharField(max_length=100,default=None,null=True,blank=True)
    subcompo = models.CharField(max_length=100,default=None,null=True,blank=True)
    activity = models.CharField(max_length=100,default=None,null=True,blank=True)
    trained = models.CharField(max_length=50, null=True, blank=True)
    experienced = models.CharField(max_length=50, null=True, blank=True)
    capacity = models.CharField(max_length=100,default=None,null=True,blank=True)
    capital_details =  models.CharField(max_length=1000, null=True, blank=True)
    nounits = models.CharField(max_length=100,default=None,null=True,blank=True)
    unitcost = models.CharField(max_length=100,default=None,null=True,blank=True)
    tocost = models.CharField(max_length=100,default=None,null=True,blank=True)
    operation_details =  models.CharField(max_length=1000, null=True, blank=True)
    nounits1 = models.CharField(max_length=100,default=None,null=True,blank=True)
    unitcost1 = models.CharField(max_length=100,default=None,null=True,blank=True)
    tocost1 = models.CharField(max_length=100,default=None,null=True,blank=True)
    total_details =  models.CharField(max_length=1000, null=True, blank=True)
    nounits2 = models.CharField(max_length=100,default=None,null=True,blank=True)
    unitcost2 = models.CharField(max_length=100,default=None,null=True,blank=True)
    tocost2 = models.CharField(max_length=100,default=None,null=True,blank=True)
    state_contri = models.CharField(max_length=100,default=None,null=True,blank=True)
    beni_contri = models.CharField(max_length=100,default=None,null=True,blank=True)
    banking_assi = models.CharField(max_length=100,default=None,null=True,blank=True)
    parti_bank = models.CharField(max_length=100,default=None,null=True,blank=True)
    name1 =  models.CharField(max_length=1000, null=True, blank=True)
    name2 =  models.CharField(max_length=1000, null=True, blank=True)
    name3 =  models.CharField(max_length=1000, null=True, blank=True)
    photo = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    sig = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    user=models.ForeignKey(UserModel, on_delete=models.CASCADE, null=True)
    scheme=models.ForeignKey(SchemeModel, on_delete=models.CASCADE, null=True)
    scheme_register=models.ForeignKey(SchemeRegistrationModel, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = "matsyasampada"
        

