from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from yojna.models import UserModel,SchemeModel,SchemeRegistrationModel

class samuhik_vivah(models.Model):
    sanstha_name = models.CharField(max_length=80,default=None,null=True,blank=True)
    sanstha_add = models.CharField(max_length=110,default=None,null=True,blank=True)
    date = models.DateField(default=None,null=True,blank=True)
    reg_no = models.CharField(max_length=30,default=None,null=True,blank=True)
    thikani = models.CharField(max_length=40,default=None,null=True,blank=True)
    time = models.TimeField(auto_now=False, auto_now_add=False,default=None,null=True,blank=True)
    padadhikari = models.CharField(max_length=80,default=None,null=True,blank=True)
    hudda = models.CharField(max_length=30,default=None,null=True,blank=True)
    var_name = models.CharField(max_length=80,default=None,null=True,blank=True)
    var_birhtdate = models.DateField(default=None,null=True,blank=True)
    var_age = models.IntegerField(default=None,null=True,blank=True)
    var_dharma = models.CharField(max_length=40,default=None,null=True,blank=True)
    var_jat = models.CharField(max_length=40,default=None,null=True,blank=True)
    var_potjat = models.CharField(max_length=40,default=None,null=True,blank=True)
    var_edu = models.CharField(max_length=70,default=None,null=True,blank=True)
    var_add = models.CharField(max_length=60,default=None,null=True,blank=True)
    var_gav = models.CharField(max_length=30,default=None,null=True,blank=True)
    var_tal = models.CharField(max_length=25,default=None,null=True,blank=True)
    var_dist = models.CharField(max_length=25,default=None,null=True,blank=True)
    var_mobile = PhoneNumberField(unique=True, blank=True)
    vadhu_name = models.CharField(max_length=80,default=None,null=True,blank=True)
    vadhu_birhtdate = models.DateField(default=None,null=True,blank=True)
    vadhu_age = models.IntegerField(default=None,null=True,blank=True)
    vadhu_dharma = models.CharField(max_length=40,default=None,null=True,blank=True)
    vadhu_jat = models.CharField(max_length=40,default=None,null=True,blank=True)
    vadhu_potjat = models.CharField(max_length=40,default=None,null=True,blank=True)
    vadhu_edu = models.CharField(max_length=70,default=None,null=True,blank=True)
    vadhu_add = models.CharField(max_length=60,default=None,null=True,blank=True)
    vadhu_gav = models.CharField(max_length=30,default=None,null=True,blank=True)
    vadhu_tal = models.CharField(max_length=25,default=None,null=True,blank=True)
    vadhu_dist = models.CharField(max_length=25,default=None,null=True,blank=True)
    vadhu_mobile = PhoneNumberField(unique=True, blank=True)
    tapal_add = models.CharField(max_length=80,default=None,null=True,blank=True)
    niwas = PhoneNumberField(unique=True, blank=True)
    karyalay = PhoneNumberField(unique=True, blank=True)
    other = PhoneNumberField(unique=True, blank=True)
    sanstha = models.CharField(max_length=100,default=None,null=True,blank=True)
    vivah_thikan = models.CharField(max_length=50,default=None,null=True,blank=True)
    vivahdate = models.DateField(default=None,null=True,blank=True)
    vivah_type = models.CharField(max_length=6,default=None,null=True,blank=True)
    var_firstvivah = models.CharField(default=None,null=True,blank=True,max_length=4)
    vadhu_firstvivah = models.CharField(default=None,null=True,blank=True,max_length=4)
    var_vidur = models.CharField(default=None,null=True,blank=True,max_length=4)
    vadhu_vidhva = models.CharField(default=None,null=True,blank=True,max_length=4)
    bfor_yojna = models.CharField(default=None,null=True,blank=True,max_length=4)
    anya_zp = models.CharField(default=None,null=True,blank=True,max_length=4)
    dinank = models.DateField(default=None,null=True,blank=True)
    place = models.CharField(max_length=50,default=None,null=True,blank=True)
    var_nm = models.CharField(max_length=50,default=None,null=True,blank=True)
    var_sign = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    var_photo = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    vadhu_nm = models.CharField(max_length=50,default=None,null=True,blank=True)
    vadhu_sign = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    vadhu_photo = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)

    user=models.ForeignKey(UserModel, on_delete=models.CASCADE, null=True)
    scheme=models.ForeignKey(SchemeModel, on_delete=models.CASCADE, null=True)
    scheme_register=models.ForeignKey(SchemeRegistrationModel, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = "samuhik_vivah"
    def __str__(self) -> str:
        return str(self.var_name)