from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from yojna.models import SchemeModel,SchemeRegistrationModel,UserModel

class shubh_vivah(models.Model):
    name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    sam_patta = models.CharField(max_length=1000, null=True, blank=True)
    post= models.CharField(max_length=100,null=True, blank=True, default=None)
    taluka= models.CharField(max_length=100,null=True, blank=True, default=None)
    buisness = models.CharField(max_length=1000, null=True, blank=True)
    girl_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    age =  models.CharField(max_length=100, null=True, blank=True)
    vivah_date = models.DateField(default=None,null=True,blank=True)
    sanstha= models.CharField(max_length=1000,null=True, blank=True, default=None)
    adhaar_no = models.CharField(max_length=100, null=True, blank=True)
    bank_name = models.CharField(max_length=100, null=True, blank=True)
    acc_no = models.CharField(max_length=100, null=True, blank=True)
    ifsc = models.CharField(max_length=100, null=True, blank=True)
    name1= models.CharField(max_length=1000,null=True, blank=True, default=None)
    form_date = models.DateField(default=None,null=True,blank=True)
    signature = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    var_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    age1 =  models.CharField(max_length=100, null=True, blank=True)
    birth_date = models.DateField(default=None,null=True,blank=True)
    education = models.CharField(max_length=1000, null=True, blank=True)
    gav= models.CharField(max_length=100,null=True, blank=True, default=None)
    taluka1= models.CharField(max_length=100,null=True, blank=True, default=None)
    jilha= models.CharField(max_length=100,null=True, blank=True, default=None)
    mobile_number = PhoneNumberField( blank=True)
    palak_patta = models.CharField(max_length=1000, null=True, blank=True)
    mobile_number1 = PhoneNumberField( blank=True)
    mobile_number2 = PhoneNumberField( blank=True)
    var_photo = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    vadhu_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    age2 =  models.CharField(max_length=100, null=True, blank=True)
    birth_date1 = models.DateField(default=None,null=True,blank=True)
    education1 = models.CharField(max_length=1000, null=True, blank=True)
    gav1= models.CharField(max_length=100,null=True, blank=True, default=None)
    taluka2= models.CharField(max_length=100,null=True, blank=True, default=None)
    jilha1= models.CharField(max_length=100,null=True, blank=True, default=None)
    mobile_number3 = PhoneNumberField( blank=True)
    palak_patta1 = models.CharField(max_length=1000, null=True, blank=True)
    mobile_number4 = PhoneNumberField( blank=True)
    mobile_number5 = PhoneNumberField( blank=True)
    vadhu_photo = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    sans_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    thikan= models.CharField(max_length=1000,null=True, blank=True, default=None)
    tarikh = models.DateField(default=None,null=True,blank=True)
    padhat= models.CharField(max_length=100,null=True, blank=True, default=None)
    var = models.BooleanField(default=None,null=True,blank=True)
    vadhu = models.BooleanField(default=None,null=True,blank=True)
    vidhva = models.BooleanField(default=None,null=True,blank=True)
    vidur = models.BooleanField(default=None,null=True,blank=True)
    arthsahayya = models.BooleanField(default=None,null=True,blank=True)
    arj = models.BooleanField(default=None,null=True,blank=True)
    var_sign = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    vadhu_sign = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    user=models.ForeignKey(UserModel, on_delete=models.CASCADE, null=True)
    scheme=models.ForeignKey(SchemeModel, on_delete=models.CASCADE, null=True)
    scheme_register=models.ForeignKey(SchemeRegistrationModel, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = "shubh_vivah"
        

