from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from yojna.models import UserModel,SchemeModel,SchemeRegistrationModel

class shubhmangal_nondni(models.Model):
    name = models.CharField(max_length=60,default=None,null=True,blank=True)
    address = models.CharField(max_length=100,default=None,null=True,blank=True)
    mobile = PhoneNumberField(unique=True, blank=True)
    shet_mahila = models.CharField(max_length=25,default=None,null=True,blank=True)
    dinank = models.DateField(default=None,null=True,blank=True)
    yethe = models.CharField(max_length=35,default=None,null=True,blank=True)
    bank = models.CharField(max_length=50, default=None,null=True,blank=True)
    acc_no = models.BigIntegerField(default=None,null=True,blank=True)
    branch = models.CharField(default=None,null=True,blank=True,max_length=30)
    ifsc = models.CharField(default=None,null=True,blank=True,max_length=18)
    adharno = models.BigIntegerField(default=None,null=True,blank=True)
    vadh = models.CharField(max_length=9,default=None,null=True,blank=True)
    nav = models.CharField(default=None,null=True,blank=True,max_length=50)
    swakshari = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    var_name= models.CharField(max_length=80,null=True, blank=True, default=None)
    age1 =  models.CharField(max_length=4, null=True, blank=True)
    birth_date = models.DateField(default=None,null=True,blank=True)
    education = models.CharField(max_length=80, null=True, blank=True)
    gav= models.CharField(max_length=40,null=True, blank=True, default=None)
    taluka1= models.CharField(max_length=25,null=True, blank=True, default=None)
    jilha= models.CharField(max_length=20,null=True, blank=True, default=None)
    mobile_number = PhoneNumberField( blank=True)
    palak_patta = models.CharField(max_length=120, null=True, blank=True)
    mobile_number1 = PhoneNumberField( blank=True)
    mobile_number2 = PhoneNumberField( blank=True)
    var_photo = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    vadhu_name= models.CharField(max_length=80,null=True, blank=True, default=None)
    age2 =  models.CharField(max_length=4, null=True, blank=True)
    birth_date1 = models.DateField(default=None,null=True,blank=True)
    education1 = models.CharField(max_length=80, null=True, blank=True)
    gav1= models.CharField(max_length=40,null=True, blank=True, default=None)
    taluka2= models.CharField(max_length=25,null=True, blank=True, default=None)
    jilha1= models.CharField(max_length=20,null=True, blank=True, default=None)
    mobile_number3 = PhoneNumberField( blank=True)
    palak_patta1 = models.CharField(max_length=120, null=True, blank=True)
    mobile_number4 = PhoneNumberField( blank=True)
    mobile_number5 = PhoneNumberField( blank=True)
    vadhu_photo = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    sans_name= models.CharField(max_length=160,null=True, blank=True, default=None)
    thikan= models.CharField(max_length=50,null=True, blank=True, default=None)
    tarikh = models.DateField(default=None,null=True,blank=True)
    padhat= models.CharField(max_length=8,null=True, blank=True, default=None)
    var_pratham = models.CharField(max_length=4,null=True, blank=True, default=None)
    vadhu_pratham = models.CharField(max_length=4,null=True, blank=True, default=None)
    var_vidur = models.CharField(max_length=4,null=True, blank=True, default=None)
    vadhu_vidhva = models.CharField(max_length=4,null=True, blank=True, default=None)
    arthsahayya = models.CharField(max_length=4,null=True, blank=True, default=None)
    arj = models.CharField(max_length=4,null=True, blank=True, default=None)
    var_sign = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    vadhu_sign = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    
    user=models.ForeignKey(UserModel, on_delete=models.CASCADE, null=True)
    scheme=models.ForeignKey(SchemeModel, on_delete=models.CASCADE, null=True)
    scheme_register=models.ForeignKey(SchemeRegistrationModel, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = "shubhmangal_nondni"
    def __str__(self) -> str:
        return str(self.name)