from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from yojna.models import SchemeModel,SchemeRegistrationModel,UserModel


class sudharitbij(models.Model):
    prakrn_no = models.CharField(max_length=30,null=True, blank=True, default=None)
    pra_date = models.DateField(default=None,null=True,blank=True)
    fullname = models.CharField(max_length=500,null=True, blank=True, default=None)
    address = models.CharField(max_length=1000,null=True, blank=True, default=None)
    pincode = models.IntegerField(null=True, blank=True, default=None)
    tel_no = PhoneNumberField(blank=True)
    mobile_no = PhoneNumberField(blank=True)
    bformarry_name = models.CharField(max_length=300,null=True, blank=True, default=None)
    qual = models.CharField(max_length=500,null=True, blank=True, default=None)
    birthdate = models.DateField(default=None,null=True,blank=True)
    age = models.CharField(max_length=50,null=True, blank=True, default=None)
    varg_jat = models.CharField(max_length=50,null=True, blank=True, default=None)
    certificate = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    current_edu = models.CharField(max_length=50,null=True, blank=True, default=None)
    current_job = models.CharField(max_length=50,null=True, blank=True, default=None)
    business = models.CharField(max_length=50,null=True, blank=True, default=None)
    school_nmadrs = models.CharField(max_length=1000,null=True, blank=True, default=None)
    college_nmadrs = models.CharField(max_length=1000,null=True, blank=True, default=None)
    edu_leave = models.IntegerField(null=True, blank=True, default=None)
    lastexam = models.CharField(max_length=1000,null=True, blank=True, default=None)
    doing = models.CharField(max_length=200,null=True, blank=True, default=None)
    loan = models.CharField(max_length=50,null=True, blank=True, default=None)
    yojna_nm = models.CharField(max_length=1000,null=True, blank=True, default=None)
    technical_edu = models.CharField(max_length=1000,null=True, blank=True, default=None)
    fatherhusband_name = models.CharField(max_length=200,null=True, blank=True, default=None)
    fatherhusband_address = models.CharField(max_length=300,null=True, blank=True, default=None)
    sheti = models.CharField(max_length=500,null=True, blank=True, default=None)
    vyavsay = models.CharField(max_length=500,null=True, blank=True, default=None)
    naukri = models.CharField(max_length=500,null=True, blank=True, default=None)
    living_homeprice = models.CharField(max_length=100,null=True, blank=True, default=None)
    sheti_hector = models.CharField(max_length=250,null=True, blank=True, default=None)
    sheti_hectorprice = models.CharField(max_length=100,null=True, blank=True, default=None)
    vyavsay_name = models.CharField(max_length=100,null=True, blank=True, default=None)
    plotarea_name = models.CharField(max_length=200,null=True, blank=True, default=None)
    plotarea_price = models.CharField(max_length=100,null=True, blank=True, default=None)
    arja_name = models.CharField(max_length=100,null=True, blank=True, default=None)
    arja_age = models.IntegerField(null=True, blank=True, default=None)
    fathername = models.CharField(max_length=100,null=True, blank=True, default=None)
    father_age = models.IntegerField(null=True, blank=True, default=None)
    mothername = models.CharField(max_length=100,null=True, blank=True, default=None)
    mother_age = models.IntegerField(null=True, blank=True, default=None)
    bro_sisname1 = models.CharField(max_length=100,null=True, blank=True, default=None)
    bro_sisage1 = models.IntegerField(null=True, blank=True, default=None)
    bro_sisname2 = models.CharField(max_length=100,null=True, blank=True, default=None)
    bro_sisage2 = models.IntegerField(null=True, blank=True, default=None)
    bro_sisname3 = models.CharField(max_length=100,null=True, blank=True, default=None)
    bro_sisage3 = models.IntegerField(null=True, blank=True, default=None)
    huswife_name = models.CharField(max_length=100,null=True, blank=True, default=None)
    huswife_age = models.IntegerField(null=True, blank=True, default=None)
    any_loan = models.CharField(max_length=500,null=True, blank=True, default=None)
    rationno_date = models.CharField(max_length=150,null=True, blank=True, default=None)
    adhaar_no = models.CharField(max_length=16,null=True, blank=True, default=None)
    serviceno_date = models.CharField(max_length=80,null=True, blank=True, default=None)
    olakh1 = models.CharField(max_length=300,null=True, blank=True, default=None)
    olakh2 = models.CharField(max_length=300,null=True, blank=True, default=None)
    malmatta = models.CharField(max_length=500 ,null=True, blank=True, default=None)
    malak_name = models.CharField(max_length=100 ,null=True, blank=True, default=None)
    jamanatdar1 = models.CharField(max_length=400,null=True, blank=True, default=None)
    jamanatdar2 = models.CharField(max_length=400,null=True, blank=True, default=None)
    bankname_ac = models.CharField(max_length=150,null=True, blank=True, default=None)
    arjadar_date = models.DateField(default=None,null=True,blank=True)
    arjadar_sign = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    fatherhusband_date = models.DateField(default=None,null=True,blank=True)
    fatherhusband_sign = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    udyogname = models.CharField(max_length=150 ,null=True, blank=True, default=None)
    udyogaddress = models.CharField(max_length=1000,null=True, blank=True, default=None)
    dukan = models.CharField(max_length=50,null=True, blank=True, default=None)
    manakname_address = models.CharField(max_length=450 ,null=True, blank=True, default=None)
    mobno = PhoneNumberField(blank=True)
    pra_rent = models.CharField(max_length=100 ,null=True, blank=True, default=None)
    samatipatra = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    niwad = models.CharField(max_length=600 ,null=True, blank=True, default=None)
    shed = models.CharField(max_length=100 ,null=True, blank=True, default=None)
    machines = models.CharField(max_length=100 ,null=True, blank=True, default=None)
    furniture = models.CharField(max_length=100 ,null=True, blank=True, default=None)
    start_mal = models.CharField(max_length=100 ,null=True, blank=True, default=None)
    milk_animal = models.CharField(max_length=100 ,null=True, blank=True, default=None)
    light = models.CharField(max_length=100 ,null=True, blank=True, default=None)
    other = models.CharField(max_length=100 ,null=True, blank=True, default=None)
    total_karz = models.CharField(max_length=100 ,null=True, blank=True, default=None)
    loan_bank = models.CharField(max_length=150,null=True, blank=True, default=None)
    bank_karz = models.CharField(max_length=100 ,null=True, blank=True, default=None)
    jilha_udyog = models.CharField(max_length=100 ,null=True, blank=True, default=None)
    swata_bhandwal = models.CharField(max_length=100 ,null=True, blank=True, default=None)
    totla_amount = models.CharField(max_length=100 ,null=True, blank=True, default=None)
    machine_nameaddress = models.CharField(max_length=700 ,null=True, blank=True, default=None)
    electricity_need = models.CharField(max_length=300 ,null=True, blank=True, default=None)
    rozgar = models.CharField(max_length=400 ,null=True, blank=True, default=None)
    monthly_sale = models.CharField(max_length=200 ,null=True, blank=True, default=None)
    masik_kharch = models.CharField(max_length=200 ,null=True, blank=True, default=None)
    dhokla_nafa = models.CharField(max_length=200 ,null=True, blank=True, default=None)
    bank_hafta = models.CharField(max_length=200 ,null=True, blank=True, default=None)
    kutumb_kharch = models.CharField(max_length=200 ,null=True, blank=True, default=None)
    final_sign = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    sampurn_nav = models.CharField(max_length=200 ,null=True, blank=True, default=None)
    photo = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)

    user=models.ForeignKey(UserModel, on_delete=models.CASCADE, null=True)
    scheme=models.ForeignKey(SchemeModel, on_delete=models.CASCADE, null=True)
    scheme_register=models.ForeignKey(SchemeRegistrationModel, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = "sudharitbij"
        

