from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from yojna.models import SchemeModel,SchemeRegistrationModel,UserModel

class swadhar_yoj(models.Model):
    place1= models.CharField(max_length=100,null=True, blank=True, default=None)
    end_date1 = models.DateField(default=None,null=True,blank=True)
    arjname= models.CharField(max_length=1000,null=True, blank=True, default=None)
    mob_number = PhoneNumberField( blank=True)
    adhar = models.BigIntegerField(default=None,null=True,blank=True)
    signature1 = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    photo = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    sur_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    fa_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    name1= models.CharField(max_length=1000,null=True, blank=True, default=None)
    sur_name1= models.CharField(max_length=1000,null=True, blank=True, default=None)
    fa_name1= models.CharField(max_length=1000,null=True, blank=True, default=None)
    hus_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    mo_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    pravarg= models.CharField(max_length=100,null=True, blank=True, default=None)
    pot= models.CharField(max_length=100,null=True, blank=True, default=None)
    ghar_kr= models.CharField(max_length=100,null=True, blank=True, default=None)
    rasta= models.CharField(max_length=100,null=True, blank=True, default=None)
    khun= models.CharField(max_length=100,null=True, blank=True, default=None)
    gav= models.CharField(max_length=100,null=True, blank=True, default=None)
    taluka= models.CharField(max_length=100,null=True, blank=True, default=None)
    jilha= models.CharField(max_length=100,null=True, blank=True, default=None)
    pin = models.IntegerField(default=None,null=True,blank=True)
    praman= models.CharField(max_length=100,null=True, blank=True, default=None)
    dakhla_date = models.DateField(default=None,null=True,blank=True)
    karya_name= models.CharField(max_length=100,null=True, blank=True, default=None)
    mobile_number = PhoneNumberField( blank=True)
    divyang= models.CharField(max_length=1000,null=True, blank=True, default=None)
    jilha_name= models.CharField(max_length=100,null=True, blank=True, default=None)
    praman1= models.CharField(max_length=100,null=True, blank=True, default=None)
    jari_date = models.DateField(default=None,null=True,blank=True)
    jat= models.CharField(max_length=100,null=True, blank=True, default=None)
    gav1= models.CharField(max_length=100,null=True, blank=True, default=None)
    taluka1= models.CharField(max_length=100,null=True, blank=True, default=None)
    jilha1= models.CharField(max_length=100,null=True, blank=True, default=None)
    adhar_card_no = models.BigIntegerField(default=None,null=True,blank=True)
    adhar_patta= models.CharField(max_length=1000,null=True, blank=True, default=None)
    bank_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    shakha= models.CharField(max_length=100,null=True, blank=True, default=None)
    acc_no= models.CharField(max_length=100,null=True, blank=True, default=None)
    ifsc= models.CharField(max_length=100,null=True, blank=True, default=None)
    purava = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    maha_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    maha_patta= models.CharField(max_length=1000,null=True, blank=True, default=None)
    idno= models.CharField(max_length=100,null=True, blank=True, default=None)
    abhyas_name= models.CharField(max_length=100,null=True, blank=True, default=None)
    year= models.CharField(max_length=100,null=True, blank=True, default=None)
    pravesh_date = models.DateField(default=None,null=True,blank=True)
    kalavadhi= models.CharField(max_length=100,null=True, blank=True, default=None)
    graduation= models.CharField(max_length=100,null=True, blank=True, default=None)
    pravesh_date1 = models.CharField(max_length=100,null=True, blank=True, default=None)
    uttirna= models.CharField(max_length=100,null=True, blank=True, default=None)
    ekun_gun= models.CharField(max_length=100,null=True, blank=True, default=None)
    prapta_gun= models.CharField(max_length=100,null=True, blank=True, default=None)
    takka= models.CharField(max_length=100,null=True, blank=True, default=None)
    pravesh_date2 = models.CharField(max_length=100,null=True, blank=True, default=None)
    uttirna1= models.CharField(max_length=100,null=True, blank=True, default=None)
    ekun_gun1= models.CharField(max_length=100,null=True, blank=True, default=None)
    prapta_gun1= models.CharField(max_length=100,null=True, blank=True, default=None)
    takka1= models.CharField(max_length=100,null=True, blank=True, default=None)
    pravesh_date3 = models.CharField(max_length=100,null=True, blank=True, default=None)
    uttirna2= models.CharField(max_length=100,null=True, blank=True, default=None)
    ekun_gun2= models.CharField(max_length=100,null=True, blank=True, default=None)
    prapta_gun2= models.CharField(max_length=100,null=True, blank=True, default=None)
    takka2= models.CharField(max_length=100,null=True, blank=True, default=None)
    fee = models.CharField(default=None,null=True,blank=True,max_length=50)
    userid= models.CharField(max_length=100,null=True, blank=True, default=None)
    palak_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    nate= models.CharField(max_length=1000,null=True, blank=True, default=None)
    mrutyu_purava = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    business= models.CharField(max_length=1000,null=True, blank=True, default=None)
    business_patta= models.CharField(max_length=1000,null=True, blank=True, default=None)
    income= models.CharField(max_length=100,null=True, blank=True, default=None)
    income_yr= models.CharField(max_length=100,null=True, blank=True, default=None)
    place= models.CharField(max_length=100,null=True, blank=True, default=None)
    end_date = models.DateField(default=None,null=True,blank=True)
    sakshi1= models.CharField(max_length=100,null=True, blank=True, default=None)
    sakshi2= models.CharField(max_length=100,null=True, blank=True, default=None)
    sakshi1_sign = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    sakshi2_sign = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    signature = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    user=models.ForeignKey(UserModel, on_delete=models.CASCADE, null=True)
    scheme=models.ForeignKey(SchemeModel, on_delete=models.CASCADE, null=True)
    scheme_register=models.ForeignKey(SchemeRegistrationModel, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = "swadhar_yoj"
        

