from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from yojna.models import UserModel,SchemeModel,SchemeRegistrationModel

class swayamrojgar_divyang(models.Model):
    name = models.CharField(max_length=80,default=None,null=True,blank=True)
    address = models.CharField(default=None,null=True,blank=True,max_length=200)
    fa_husname = models.CharField(max_length=100,default=None,null=True,blank=True)
    patra_address = models.CharField(default=None,null=True,blank=True,max_length=200)
    age = models.IntegerField(default=None,null=True,blank=True)
    birthdate = models.DateField(default=None,null=True,blank=True)
    daridrya_yn = models.CharField(default=None,null=True,blank=True,max_length=10)
    daridrya_num = models.CharField(default=None,null=True,blank=True,max_length=25)
    apang_type = models.CharField(default=None,null=True,blank=True,max_length=80)
    apang_swarup = models.CharField(default=None,null=True,blank=True,max_length=80)
    apang_certificate = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    certificate_yn = models.CharField(default=None,null=True,blank=True,max_length=10)
    vyavsay = models.CharField(default=None,null=True,blank=True,max_length=70)
    income = models.IntegerField(default=None,null=True,blank=True)
    olakh1 = models.CharField(default=None,null=True,blank=True,max_length=150)
    olakh2 = models.CharField(default=None,null=True,blank=True,max_length=150)
    photo_yn = models.CharField(default=None,null=True,blank=True,max_length=10)
    education = models.CharField(default=None,null=True,blank=True,max_length=80)
    shaley_edu = models.CharField(default=None,null=True,blank=True,max_length=250)
    technical_edu = models.CharField(default=None,null=True,blank=True,max_length=250)
    other_edu = models.CharField(default=None,null=True,blank=True,max_length=80)
    naukri_exp = models.CharField(default=None,null=True,blank=True,max_length=100)
    business_exp = models.CharField(default=None,null=True,blank=True,max_length=120)
    samaj_exp = models.CharField(default=None,null=True,blank=True,max_length=100)
    ration_yn = models.CharField(default=None,null=True,blank=True,max_length=10)
    arja_vyavsay = models.CharField(default=None,null=True,blank=True,max_length=100)
    vyavsay_swarup = models.CharField(default=None,null=True,blank=True,max_length=100)
    vyavsay_ghatna = models.CharField(default=None,null=True,blank=True,max_length=100)
    malak_bhagidar = models.CharField(default=None,null=True,blank=True,max_length=350)
    vyavsay_reason = models.CharField(default=None,null=True,blank=True,max_length=100)
    bhandval = models.CharField(default=None,null=True,blank=True,max_length=100)
    kayam_bhandval = models.CharField(default=None,null=True,blank=True,max_length=100)
    khelte_bhandval = models.CharField(default=None,null=True,blank=True,max_length=100)
    yojna_tartud = models.CharField(default=None,null=True,blank=True,max_length=150)
    guntavlele_bhandval = models.CharField(default=None,null=True,blank=True,max_length=150)
    prakalp_yn = models.CharField(default=None,null=True,blank=True,max_length=10)
    samajkalyan_khate = models.CharField(default=None,null=True,blank=True,max_length=70)
    spardha = models.CharField(default=None,null=True,blank=True,max_length=350)
    mal_vikri = models.CharField(default=None,null=True,blank=True,max_length=80)
    other_help = models.CharField(default=None,null=True,blank=True,max_length=100)
    other_arza = models.CharField(default=None,null=True,blank=True,max_length=150)
    dinank = models.DateField(default=None,null=True,blank=True)
    place = models.CharField(default=None,null=True,blank=True,max_length=50)
    signature = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    photo = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)    
    
    user=models.ForeignKey(UserModel, on_delete=models.CASCADE, null=True)
    scheme=models.ForeignKey(SchemeModel, on_delete=models.CASCADE, null=True)
    scheme_register=models.ForeignKey(SchemeRegistrationModel, on_delete=models.CASCADE, null=True)
    
    class Meta:
        db_table = "swayamrojgar_divyang"
    def __str__(self) -> str:
        return str(self.name)