from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from yojna.models import SchemeModel,SchemeRegistrationModel,UserModel

class zakir_hus(models.Model):
    madarsa_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    madarsa_patta= models.CharField(max_length=1000,null=True, blank=True, default=None)
    mobile_number = PhoneNumberField( blank=True)
    email_id = models.EmailField(null=False, blank=False, default=None)
    sanstha_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    sanstha_patta = models.CharField(max_length=1000, null=True, blank=True)
    mobile_number1 = PhoneNumberField( blank=True)
    email_id1 = models.EmailField(null=False, blank=False, default=None)
    adhyaksh_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    adhyaksh_patta = models.CharField(max_length=1000, null=True, blank=True)
    mobile_number2 = PhoneNumberField( blank=True)
    sachiv_name= models.CharField(max_length=1000,null=True, blank=True, default=None)
    sachiv_patta = models.CharField(max_length=1000, null=True, blank=True)
    mobile_number3 = PhoneNumberField( blank=True)
    nondani_kr = models.CharField(max_length=100, null=True, blank=True)
    bank_name = models.CharField(max_length=100, null=True, blank=True)
    acc_no = models.CharField(max_length=100, null=True, blank=True)
    ifsc = models.CharField(max_length=100, null=True, blank=True)
    patsankhya = models.CharField(max_length=100, null=True, blank=True)
    madhyam = models.CharField(max_length=100, null=True, blank=True)
    e_mahiti = models.CharField(max_length=1000, null=True, blank=True)
    soi_suvidha = models.CharField(max_length=100, null=True, blank=True)
    kho_sankhya1 = models.CharField(max_length=100, null=True, blank=True)
    kho_sankhya2 = models.CharField(max_length=100, null=True, blank=True)
    kho_sankhya3 = models.CharField(max_length=100, null=True, blank=True)
    kho_sankhya4 = models.CharField(max_length=100, null=True, blank=True)
    kshetrafal1 = models.CharField(max_length=100, null=True, blank=True)
    kshetrafal2 = models.CharField(max_length=100, null=True, blank=True)
    kshetrafal3 = models.CharField(max_length=100, null=True, blank=True)
    kshetrafal4 = models.CharField(max_length=100, null=True, blank=True)
    pinych_pani = models.CharField(max_length=100, null=True, blank=True)
    malkichi = models.CharField(max_length=50, null=True, blank=True)
    utara = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    upkram = models.CharField(max_length=50, null=True, blank=True)
    tapshil = models.CharField(max_length=100, null=True, blank=True)
    nutanikaran1 = models.CharField(max_length=100, null=True, blank=True)
    nutanikaran2 = models.CharField(max_length=100, null=True, blank=True)
    nutanikaran3 = models.CharField(max_length=100, null=True, blank=True)
    nutanikaran4 = models.CharField(max_length=100, null=True, blank=True)
    dagduji1 = models.CharField(max_length=100, null=True, blank=True)
    dagduji2 = models.CharField(max_length=100, null=True, blank=True)
    dagduji3 = models.CharField(max_length=100, null=True, blank=True)
    dagduji4 = models.CharField(max_length=100, null=True, blank=True)
    chhat1 = models.CharField(max_length=100, null=True, blank=True)
    chhat2 = models.CharField(max_length=100, null=True, blank=True)
    chhat3 = models.CharField(max_length=100, null=True, blank=True)
    chhat4 = models.CharField(max_length=100, null=True, blank=True)
    farshi1 = models.CharField(max_length=100, null=True, blank=True)
    farshi2 = models.CharField(max_length=100, null=True, blank=True)
    farshi3 = models.CharField(max_length=100, null=True, blank=True)
    farshi4 = models.CharField(max_length=100, null=True, blank=True)
    itar1 = models.CharField(max_length=100, null=True, blank=True)
    itar2 = models.CharField(max_length=100, null=True, blank=True)
    itar3 = models.CharField(max_length=100, null=True, blank=True)
    itar4 = models.CharField(max_length=100, null=True, blank=True)
    kooler1 = models.CharField(max_length=100, null=True, blank=True)
    kooler2 = models.CharField(max_length=100, null=True, blank=True)
    kooler3 = models.CharField(max_length=100, null=True, blank=True)
    kooler4 = models.CharField(max_length=100, null=True, blank=True)
    swachhata1 = models.CharField(max_length=100, null=True, blank=True)
    swachhata2 = models.CharField(max_length=100, null=True, blank=True)
    swachhata3 = models.CharField(max_length=100, null=True, blank=True)
    swachhata4 = models.CharField(max_length=100, null=True, blank=True)
    swachhtagruhe1 = models.CharField(max_length=100, null=True, blank=True)
    swachhtagruhe2 = models.CharField(max_length=100, null=True, blank=True)
    swachhtagruhe3 = models.CharField(max_length=100, null=True, blank=True)
    swachhtagruhe4 = models.CharField(max_length=100, null=True, blank=True)
    furniture1 = models.CharField(max_length=100, null=True, blank=True)
    furniture2 = models.CharField(max_length=100, null=True, blank=True)
    furniture3 = models.CharField(max_length=100, null=True, blank=True)
    furniture4 = models.CharField(max_length=100, null=True, blank=True)
    benches1 = models.CharField(max_length=100, null=True, blank=True)
    benches2 = models.CharField(max_length=100, null=True, blank=True)
    benches3 = models.CharField(max_length=100, null=True, blank=True)
    benches4 = models.CharField(max_length=100, null=True, blank=True)
    inverter1 = models.CharField(max_length=100, null=True, blank=True)
    inverter2 = models.CharField(max_length=100, null=True, blank=True)
    inverter3 = models.CharField(max_length=100, null=True, blank=True)
    inverter4 = models.CharField(max_length=100, null=True, blank=True)
    imarat1 = models.CharField(max_length=100, null=True, blank=True)
    imarat2 = models.CharField(max_length=100, null=True, blank=True)
    imarat3 = models.CharField(max_length=100, null=True, blank=True)
    imarat4 = models.CharField(max_length=100, null=True, blank=True)
    sanganak1 = models.CharField(max_length=100, null=True, blank=True)
    sanganak2 = models.CharField(max_length=100, null=True, blank=True)
    sanganak3 = models.CharField(max_length=100, null=True, blank=True)
    sanganak4 = models.CharField(max_length=100, null=True, blank=True)
    sankhya1 = models.CharField(max_length=100, null=True, blank=True)
    sankhya2 = models.CharField(max_length=100, null=True, blank=True)
    sankhya3 = models.CharField(max_length=100, null=True, blank=True)
    sankhya4 = models.CharField(max_length=100, null=True, blank=True)
    printers1 = models.CharField(max_length=100, null=True, blank=True)
    printers2 = models.CharField(max_length=100, null=True, blank=True)
    printers3 = models.CharField(max_length=100, null=True, blank=True)
    printers4 = models.CharField(max_length=100, null=True, blank=True)
    software1 = models.CharField(max_length=100, null=True, blank=True)
    software2 = models.CharField(max_length=100, null=True, blank=True)
    software3 = models.CharField(max_length=100, null=True, blank=True)
    software4 = models.CharField(max_length=100, null=True, blank=True)
    itar_sahity1 = models.CharField(max_length=100, null=True, blank=True)
    itar_sahity2 = models.CharField(max_length=100, null=True, blank=True)
    itar_sahity3 = models.CharField(max_length=100, null=True, blank=True)
    itar_sahity4 = models.CharField(max_length=100, null=True, blank=True)
    prayogshala1 = models.CharField(max_length=100, null=True, blank=True)
    prayogshala2 = models.CharField(max_length=100, null=True, blank=True)
    prayogshala3 = models.CharField(max_length=100, null=True, blank=True)
    prayogshala4 = models.CharField(max_length=100, null=True, blank=True)
    granthalay1 = models.CharField(max_length=100, null=True, blank=True)
    granthalay2 = models.CharField(max_length=100, null=True, blank=True)
    granthalay3 = models.CharField(max_length=100, null=True, blank=True)
    granthalay4 = models.CharField(max_length=100, null=True, blank=True)
    book_bank1 = models.CharField(max_length=100, null=True, blank=True)
    book_bank2 = models.CharField(max_length=100, null=True, blank=True)
    book_bank3 = models.CharField(max_length=100, null=True, blank=True)
    book_bank4 = models.CharField(max_length=100, null=True, blank=True)
    pustke_khredi1 = models.CharField(max_length=100, null=True, blank=True)
    pustke_khredi2 = models.CharField(max_length=100, null=True, blank=True)
    pustke_khredi3 = models.CharField(max_length=100, null=True, blank=True)
    pustke_khredi4 = models.CharField(max_length=100, null=True, blank=True)
    mandhan = models.CharField(max_length=100, null=True, blank=True)
    magni = models.CharField(max_length=100, null=True, blank=True)
    mi = models.CharField(max_length=100, null=True, blank=True)
    pramanit = models.CharField(max_length=100, null=True, blank=True)
    sansthedvara = models.CharField(max_length=100, null=True, blank=True)
    sanchalit = models.CharField(max_length=100, null=True, blank=True)
    hudda = models.CharField(max_length=100, null=True, blank=True)
    signature = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    name = models.CharField(max_length=1000, null=True, blank=True)
    shikka = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    photo1 = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    photo2 = models.FileField(upload_to='media/divyang_person_sign',default=None,null=True,blank=True)
    user=models.ForeignKey(UserModel, on_delete=models.CASCADE, null=True)
    scheme=models.ForeignKey(SchemeModel, on_delete=models.CASCADE, null=True)
    scheme_register=models.ForeignKey(SchemeRegistrationModel, on_delete=models.CASCADE, null=True)

    class Meta:
        db_table = "zakir_hus"
        

